### ISSUE TITLE
Pdf export stuck when browser window is scaled and timeline is zoom in

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#9277] opened 2024-05-31 10:09 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=29228&p=147423#p147423)

1. Go to pdf export demo https://bryntum.com/products/scheduler/examples/export/
2. Zoom out the browser window 
3. Zoom in the timeline 
4. Click on pdf export and export it
5. See the export is stuck

https://github.com/bryntum/support/assets/52177956/4702683a-f14f-4119-8016-af749a1f73af

**Comment by bmblb** [comment] 2024-05-31 12:40
Dupe of #9278

**Closed by bmblb** 2024-05-31 12:40 UTC
Labels: bug, pdf export, forum, OEM
