### ISSUE TITLE
[REACT] Custom column editor lose value in React 18

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6912] opened 2023-06-02 09:43 UTC
Attached app is mostly contains our basic demo code

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=25187&p=125297#p125297)

Hi.

We are building custom column editors/controls for Gantt but are experiencing loss of data.
After days of debugging we finally realized that it is the combination of React v. 18 + lack of renderers for all columns that is causing the problem.

Video demonstrating the problem + runnable sample (based on React v. 18) attached.

[Bryntum-2023-06-01-049.zip](https://github.com/bryntum/support/files/11634073/Bryntum-2023-06-01-049.zip)

https://github.com/bryntum/support/assets/7203098/deac45b7-32ee-4834-8729-792b84839fa1

**Comment by FlowIT-JIT** [comment] 2023-10-10 13:03
@matsbryntse This bug has not been fixed, it seems. It was not fixed in version 5.3.7, nor does it work in the most recent version 5.5.4 either.

Please be careful not to assume it has been fixed by testing with different values in the custom controls when attempting to verify the bug using the runnable sample in the [forum post](https://forum.bryntum.com/viewtopic.php?t=25187). The bug seems related to dirty/change logic, so the same value must be applied in every control - a common use case when working with dropdown controls.

![image](https://github.com/bryntum/support/assets/10479064/40045730-4e47-42ef-aaf5-be63b0c4d741)

**Comment by matsbryntse** [comment] 2023-10-10 13:08
We'll take another look

**Comment by jsakalos** [comment] 2023-10-10 13:25
Confirmed, it behaves as you describe @FlowIT-JIT. We'll dig into it and will fix it.

**Comment by FlowIT-JIT** [comment] 2023-10-10 18:09
Thanks @jsakalos - appreciate it 👍

**Comment by jsakalos** [comment] 2023-10-11 12:32
@FlowIT-JIT, what's going on here is that we call `this.setState()` in the editor's `setValue` method which in turn causes the React editor component to re-render. However, `setState` is asynchronous, more a request to React to update state, so the state is actually updated too late.

We need a synchronous update and component re-render which can be achieved easily with the following code of the CustomEditor:
```
import React from "react";

export default class CustomEditor extends React.Component {

    txtRef = React.createRef();

    value = '';

    //region Cell editing interface, required functions

    // Should return the value to be applied when editing finishes
    getValue() {
        return this.value;
    }

    // Current cell value + context, set when editing starts. Use it to populate your editor
    setValue(value, cellEditorContext) {
        this.value = value;
        this.forceUpdate();
    }

    // Invalid editors are note allowed to close (unless grid is so configured).
    // Implement this function to handle validation of your editor.
    isValid() {
        return true;
    }

    // Called when editing starts, to set focus at the desired place in your editor
    focus() {
        this.txtRef.current && this.txtRef.current.focus();
    }

    //endregion

    render() {
        return <input
            ref={this.txtRef}
            type="text"
            style={{ width: "100%" }}
            value={this.value || ""}
            onChange={(e) => { this.setValue(e.target.value); }}
        />
    }
}
```

Try to use this editor and let us know the results please.

**Comment by FlowIT-JIT** [comment] 2023-10-12 12:30
@jsakalos Thank you for the suggested work around.

Logging out calls to setValue(..) and getValue() confirms your suspicion - the value applied via setValue(..) is not immediately available when getValue() is called afterwards.

On the left side we have the log output when I enter 'k' in all editors. Every second value is lost.

On the right side we have the log output when I enter different letters in all editors. All values are preserved.

![image](https://github.com/bryntum/support/assets/10479064/336b9446-4361-435d-a7dd-e0740e44b74f)

A couple of thoughts:

The real problem here is probably that Gantt relies on the control to return the "original value" for a cell which is later compared to the control value when focus is lost, and if it's the same, the value is not applied/persisted. If this is indeed the case, the problem should be solved by not relying on the control to provide the original value, but instead use the value passed to setValue(..), or by reading it from the task store.

If there is no intention to change the implementation, I would suggest a change to examples/frameworks/react/javascript/basic/src/components/DemoEditor.js to use the forceUpdate() hack, with a comment explaining that this is required for controls to work properly. I would personally eliminate it, unless explicitly declared as necessary. The same goes for documenting the need to use forceUpdate() here: https://bryntum.com/products/gantt/docs/api/Grid/column/Column#config-editor

**Comment by isglass** [comment] 2023-10-17 08:37
Moving to next release since @jsakalos is afk, and custom is unblocked for the time being

**Comment by FlowIT-JIT** [comment] 2023-10-17 09:34
@isglass Thanks for keeping us posted 👍

**Comment by isglass** [comment] 2023-11-21 09:42
After discussion in the team, we have decided to update demo & docs now, keeping this ticket open to see if we in the future can refactor cell editing in our core to at some point fix it "properly".

**Comment by isglass** [comment] 2023-11-23 06:13
With next release, docs & demos will promote using the callback of `setState()` as a "fix" for this issue. This approach will let `setValue()` (and the editor calling it) wait until state is updated:

```
setValue(value: string) {
    return new Promise(resolve => this.setState({ value }, () => resolve(value)));
}
```

**Comment by jsakalos** [comment] 2023-12-18 11:30
@isglass I think we can close this ticket. The demos are already updated to use Promise in setValue of the editors.

**Closed** 2024-01-05 08:43 UTC
Labels: bug, react, premium, forum, OEM
