### ISSUE TITLE
Dragging twice with fillTicks broken

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1362] opened 2020-08-20 07:57 UTC
http://lh/bryntum-suite/Scheduler/examples/fillticks/

1. Drag "Internal project" slightly left
2. Do it again

Gets stuck where dropped second time:

<img width="473" alt="Screenshot 2020-08-20 at 09 53 59" src="https://user-images.githubusercontent.com/5415653/90732386-4f022300-e2cb-11ea-90d4-8cf7ba0ebe15.png">

**Comment by bmblb** [comment] 2020-08-20 08:04
Duplicate of #630

**Closed** 2020-08-20 08:05 UTC
Labels: bug, bugbash, duplicate
