### ISSUE TITLE
Vue.js 3 - AjaxStore - Filter Not working

### ISSUE THREAD

**Issue by guilherme-pinto-reeeliance** [bryntum/support#8788] opened 2024-03-11 20:58 UTC
When using AjaxStore Grid with Vue.js 3 + Nuxtjs 3  Bryntum grid 

"@bryntum/grid": "^5.6.8",
"@bryntum/grid-vue-3": "^5.6.8",

The server its responding normally with the filter working but the bryntum its havings this errors

We are having this problem when the user hits one character 

![Screenshot 2024-03-11 at 20 53 25](https://github.com/bryntum/support/assets/163057738/d41a2ab5-3983-4cab-8cd4-210352329964)

TypeError: Cannot read properties of undefined (reading 'dataset')
    at Proxy.processCellContent (http://localhost:3000/_nuxt/node_modules/@bryntum/grid-vue-3/src/WrapperHelperVue3.js?v=a0350e9d:52:38)
    at Proxy.renderCell (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:94800:60)
    at Proxy.render (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:94655:17)
    at Proxy.renderFromRow (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:95802:11)
    at Proxy.refresh (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:95867:8)
    at Proxy.refreshRows (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:103605:18)
    at Proxy.resumeRefresh (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:103697:14)
    at Proxy.internalOnStoreEndApplyChangeset (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:102960:10)
    at Proxy.trigger (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:5064:34)
    at Proxy.syncDataset (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:28184:8)

And when the user hits a second character this error

![Screenshot 2024-03-11 at 20 53 07](https://github.com/bryntum/support/assets/163057738/a99a61e2-f920-4ce3-960d-ae2b02aebae3)
TypeError: 'get' on proxy: property 'parser' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected '#<NumberParser>' but got '#<NumberParser>')
    at Proxy.parse (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:20878:41)
    at Proxy.changeValue (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:66566:58)
    at Proxy.set (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:1628:44)
    at Reflect.set (<anonymous>)
    at MutableReactiveHandler.set (http://localhost:3000/_nuxt/node_modules/.cache/vite/client/deps/chunk-DSIC5XJC.js?v=a0350e9d:1517:32)
    at Proxy.updateColumnFilterFields (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:83763:25)
    at Proxy.onStoreFilter (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:83877:12)
    at Proxy.trigger (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:5064:34)
    at Proxy.triggerFilterEvent (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:24876:12)
    at Proxy.afterPerformFilter (http://localhost:3000/_nuxt/node_modules/@bryntum/grid/grid.module.js?v=a0350e9d:24871:14)

After this the bryntum stop working

After Hours and Hours of debug i think i found the source of this problem
This on the `performFilter` method where did you guys have a promise `internalLoad` 

```js
const result = await me.internalLoad({}, "", (event)=>{
                me.data = event.data;
                event = silent ? null : {
                    action: "filter",
                    filters,
                    oldCount,
                    records: me.storage.values
                };
                me.afterPerformFilter(event);
                me.trigger("refresh", event);
            }
```

on my tests the start of all errors its this part.

**Comment by jsakalos** [comment] 2024-04-04 17:15
@guilherme-pinto-reeeliance, would you please post a showcase we can run and debug or the exact steps to reproduce the problem with one of our demos?

**Comment by guilherme-pinto-reeeliance** [comment] 2024-04-04 17:27
follow a repository where you find the code to reproduce the error
https://github.com/guilherme-pinto-reeeliance/vue3-bryntum-filter-error

you can find a live version here: https://vue3-bryntum-filter-error.pages.dev/

the configuration file its this one

https://github.com/guilherme-pinto-reeeliance/vue3-bryntum-filter-error/blob/17a6230e4a01b455bfa03c0fed453adea20c1e20/app.vue

**Comment by ghulamghousdev** [comment] 2024-04-04 17:31
Hi @guilherme-pinto-reeeliance,

Thanks for sharing it. We have a high prio ticket here https://github.com/bryntum/support/issues/8846. I was working on it. I have fixed the issue already, will try to push to get it merge tomorrow. You can track this issue there.

**Comment by jsakalos** [comment] 2024-04-04 17:38
Explanation: `vue: true` must be used with an appropriate renderer and it should not do anything by itself. The problem was that setting this flag but not providing the renderer caused the crash. The fix makes the code impervious to that combination. We expect it will be release in `5.6.10`. Until then just remove the vue flag.

**Comment by guilherme-pinto-reeeliance** [comment] 2024-04-04 17:45
Even with the render the problem continue. And whiteout the property set as
true, nothing is showing up.

**Comment by ghulamghousdev** [comment] 2024-04-04 18:45
@guilherme-pinto-reeeliance the test case provided by you does not include any renderer. And I have tried it in our online example with a vue renderer and issue was resolved.

**Comment by SergeyMaltsev** [comment] 2024-04-05 05:53
Closed as duplicate for resolved issue
https://github.com/bryntum/support/issues/8846

**Closed by SergeyMaltsev** 2024-04-05 05:53 UTC
Labels: resolved, high-priority
