### ISSUE TITLE
Scheduler Pro crashes when trying to undo after copy/paste multievent selection (`[CTRL + Click]`)

### ISSUE THREAD

**Issue by JonSagarminaga** [bryntum/support#6610] opened 2023-04-18 10:05 UTC
https://user-images.githubusercontent.com/55576623/232740001-5c055057-ceeb-46ef-bcfa-1120515115a7.mp4

Here is the code:

```
import React, {  useEffect, useMemo, useRef } from 'react';
import { BryntumSchedulerPro } from '@bryntum/schedulerpro-react';
import { Scheduler } from '@bryntum/schedulerpro';



const PruebaView = ()=> {
   

    const schedulerProRef = useRef<BryntumSchedulerPro>(null);
    const schedulerInstance = () => schedulerProRef.current?.instance as Scheduler;

    useEffect(() => {
        // This shows loading data
        // To load data automatically configure crudManager with `autoLoad : true`
        schedulerInstance().crudManager.load();
    });

    const memoizedConfig = useMemo(() => {
        const config =  {
            startDate  : '2018-02-07',
            endDate    : '2018-02-14',
            viewPreset : 'hourAndDay',
            enableRecurringEvents : true,
            columns    : [
                {
                    type           : 'resourceInfo',
                    text           : 'Name',
                    field          : 'name',
                    showEventCount : false,
                    width          : 150
                }
            ],
            enableUndoRedoKeys : true,
            project : {
                //  autoLoad: false,
                transport : {
                    load : {
                        url : 'data/data.json'
                    }
                },
                stm : {
                    autoRecord : true,
                }
            },

            tbar : [{
                type  : 'undoredo',
                icon  : 'b-fa-undo',
                items : {
                    transactionsCombo : {
                        width : 250,
                    }
                }
            }],
            
        }

        return config}, [])


    return (
        
            <BryntumSchedulerPro
                ref={schedulerProRef}
                {...memoizedConfig as any}
                multiEventSelect
                /> 
    )

}

export default PruebaView
```

And here the dataset:

```
{
    "success": true,
    "resources": {
        "rows": [
            { "id": "a", "name": "Arcady", "role": "Developer" },
            { "id": "b", "name": "Dave", "role": "Sales" },
            { "id": "c", "name": "Henrik", "role": "Sales" },
            { "id": "f", "name": "Celia", "role": "CEO" },
            { "id": "g", "name": "Lee", "role": "CTO" },
            { "id": "d", "name": "Madison", "role": "Developer" },
            { "id": "e", "name": "Maxim", "role": "Developer" },
            { "id": "h", "name": "Amit", "role": "Sales" },
            { "id": "i", "name": "Kate", "role": "Developer" },
            { "id": "j", "name": "Mark", "role": "Developer" },
            { "id": "k", "name": "Emilia", "role": "Developer" }
        ]
    },
    "events": {
        "rows": [
            {
                "id": 1,
                "resourceId": "a",
                "name": "Meeting #1",
                "desc": "Discuss new features",
                "startDate": "2018-02-07 11:00",
                "endDate": "2018-02-07 14:00",
                "eventType": "Meeting",
                "eventColor": "blue",
                "iconCls": "b-fa b-fa-calendar"
            }
           
        ]
    }
   
}
```

**Comment by canonic-epicure** [comment] 2023-04-18 13:13
@JonSagarminaga Hi, in which version are you observing this issue? We've recently (in 5.3.3) fixed a very similar bug: https://github.com/bryntum/support/issues/6296
Can you try to reproduce with 5.3.3 and let us know if the problem is gone?

**Comment by matsbryntse** [comment] 2023-04-18 16:16
Your account was marked as Admin (no download rights). I've changed that now, please check nightlies again?

**Comment by JonSagarminaga** [comment] 2023-04-19 08:06
> Your account was marked as Admin (no download rights). I've changed that now, please check nightlies again?

We have rights now, thanks!

@canonic-epicure we have installed the nightly build and now it doesn't crash but it seems that is not visualizing the undo actions correctly, unless you refresh de page, in this case it works right:


https://user-images.githubusercontent.com/55576623/233010086-be3b3ea9-2986-4605-9306-d4e0f5aa5131.mov

**Comment by canonic-epicure** [comment] 2023-04-19 14:59
Ok, please post a reproducible test case here? (an archive with the whole app if possible)

**Comment by JonSagarminaga** [comment] 2023-04-20 07:24
Is the same code we posted, and the same error is reproducible here also: https://bryntum.com/products/scheduler/examples/undoredo/

**Comment by canonic-epicure** [comment] 2023-04-20 07:42
Confirmed, we'll take a look, thanks for the report!

**Comment by canonic-epicure** [comment] 2023-05-01 08:51
@JonSagarminaga It seems in our example https://bryntum.com/products/scheduler/examples/undoredo/ the view is refreshed after undo just fine. However for drag-create 3 undo/redo actions are created, so user has to hit the "undo" button 3 times, before it will disappear from the view.

Can you please confirm it is the same issue you are experiencing in your code? If not, please post the whole React app with reproduction steps here?

**Comment by JonSagarminaga** [comment] 2023-05-02 10:04
@canonic-epicure In your example if you copy the event in the same line is correct, but if you copy it in another line, it doesn't refresh de page. And we have seen another bug referred to copy the event with SHIFT button, if you undo it, the two events are eliminated. 


https://user-images.githubusercontent.com/55576623/235638163-0da6292e-d99e-478b-8653-a84c9fee72b8.mp4

**Comment by canonic-epicure** [comment] 2023-05-02 12:14
Thanks for the explanations, I'll be fixing it.

**Comment by canonic-epicure** [comment] 2023-05-03 10:04
@JonSagarminaga Can you also provide some info about the other bug you mentioned - regarding copy the event with SHIFT? When I do that (CTRL+SHIFT+C), then paste, then undo - nothing special happens, same behavior as when copying w/o SHIFT.

**Comment by canonic-epicure** [comment] 2023-05-04 05:24
@JonSagarminaga It seems the view is not refreshed only when `resourceId` field of the event is used, instead of a proper `AssignmentModel` instance. If you need the workaround asap, you can make sure you data is using assignment instances instead of `resourceId` field. We'll be fixing this bug anyway of course.

**Comment by canonic-epicure** [comment] 2023-05-05 05:55
@JonSagarminaga So, the absence of the view refresh after copy-paste undo has been fixed in this ticket. I've also created a separate ticket #6699 about recording only 1 transaction for drag-create + edit, instead of 3 transactions.

Please also create a new ticket for the issue you were mentioning about the copy-paste with SHIFT button.

**Comment by JonSagarminaga** [comment] 2023-05-05 10:02
@canonic-epicure  I have created it in #6707

**Comment by canonic-epicure** [comment] 2023-05-05 10:30
Ok, great, I'll checking that one too.

**Comment by JonSagarminaga** [comment] 2023-05-05 10:31
Thanks!

**Closed as completed** 2023-05-11 08:06 UTC
Labels: bug, resolved, high-priority
