### ISSUE TITLE
Combo items and displayField should be localizable

### ISSUE THREAD

**Issue by pmiklashevych** [bryntum/support#2886] opened 2021-05-17 10:29 UTC
https://www.bryntum.com/forum/viewtopic.php?p=86765#p86765

Another [request](https://forum.bryntum.com/viewtopic.php?f=44&t=25204&p=125393#p125393)

Scheduler/examples/localization/locales/custom.locale.En.js
```
    Combo : {
        testLabel : 'my label',
        monthText : 'my month',
        weekText  : 'my week',
        dayText   : 'my day',
```
Scheduler/examples/localization/app.js
```

new Scheduler({
    tbar : [
        {
            type  : 'combo',
            label : 'L{testLabel}',
            items : [{
                value : 'monthAndYear',
                text  : 'L{monthText}'
            },
            {
                value : 'weekAndDay',
                text  : 'L{weekText}'
            },
            {
                value : 'dayAndWeek',
                text  : 'L{dayText}'
            }]
        }
    ],
```

See items are not localized. Select and item. See selected value is not localized.

Workaround:
```
LocaleManager.on({
    locale() {
        const value = scheduler.widgetMap.myCombo.value;
        scheduler.widgetMap.myCombo.value = null;
        scheduler.widgetMap.myCombo.value = value;
    }
});

new Scheduler({
    tbar : [
        {
            type  : 'combo',
            ref   : 'myCombo',
            label : 'L{testLabel}',
            displayValueRenderer(record, combo) {
                // `this` - Combo
                return record ? this.L(record.text) : '';
            },
            listItemTpl({ text }) {
                // `this` - List
                // `this.owner` - Combo
                return this.owner.L(text);
            },
            items : [{
                value : 'monthAndYear',
                text  : 'L{monthText}'
            },
            {
                value : 'weekAndDay',
                text  : 'L{weekText}'
            },
            {
                value : 'dayAndWeek',
                text  : 'L{dayText}'
            }]
        }
    ],
```

This might me related: https://github.com/bryntum/support/issues/1429

**Comment by chuckn0rris** [comment] 2023-06-05 13:24
Another [request](https://forum.bryntum.com/viewtopic.php?f=44&t=25204&p=125393#p125393)

**Comment by JockeLindberg** [comment] 2024-03-25 08:50
Closing this as it's a duplicate of https://github.com/bryntum/support/issues/1429

**Closed by JockeLindberg** 2024-03-25 08:50 UTC
Labels: bug, premium, forum, localization
