### ISSUE TITLE
clearChanges method stopped working on 5.2.1

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5510] opened 2022-11-01 20:33 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=22799&p=112811#p112811)

Check the example described by the user [here](https://forum.bryntum.com/viewtopic.php?p=112798#p112798)

> Add an item at the bottom using the text box. Check the BaseGridApp.Controls.Gantt.project.changes object
see that there is an item with a phantom id
press save in top left
now check BaseGridApp.Controls.Gantt.project.changes
the added task is still there but the Id has changed.
you can also try BaseGridApp.Controls.Gantt.project.clearChanges() which doesnt clear the tasks.

**Comment by marciogurka** [comment] 2022-11-01 20:58
User added a note 

> and a note the clearchanges works prior to sync to the server. So if you add an item and then clear changes it works. Soon as you sync it no longer goes away.

**Comment by arcady-zherdev** [comment] 2023-01-27 08:12
Your test case at https://oneplanqa.azurewebsites.net/home/repro504 no longer works.
Could you please update it so I could investigate the issue? ..Since I can't reproduce it on our examples.

**Comment by arcady-zherdev** [comment] 2023-02-09 06:00
This issue seems caused by id field mapping issue described in this ticket: https://github.com/bryntum/support/issues/412
So closing this as duplicating.

**Closed by arcady-zherdev** 2023-02-09 06:00 UTC
Labels: bug, info requested, regression, high-priority, forum
