### ISSUE TITLE
Changing viewpreset throws error when infiniteScroll enabled

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7235] opened 2023-07-28 11:18 UTC
To reproduce open this url http://lh/bryntum-suite/scheduler/examples/dragfromgrid/
Please follow the steps in the video

https://github.com/bryntum/support/assets/75997756/f08a71dc-1863-4b35-970f-972b2f24aa60

callStack
```
TimelineViewPresets.js:307 Uncaught TypeError: Cannot read properties of undefined (reading 'getTime')
    at Schedule.updateViewPreset (TimelineViewPresets.js:307:59)
    at Schedule.set (Config.js:372:34)
    at ViewPresetCombo.onSelect (ViewPresetCombo.js:152:34)
    at ViewPresetCombo.callback (Base.js:626:25)
    at ViewPresetCombo.trigger (Events.js:1389:48)
    at ViewPresetCombo.onValueCollectionChange (Combo.js:1948:25)
    at Collection.trigger (Events.js:1513:44)
    at Collection.splice (Collection.js:801:16)
    at List.onItemClick (List.js:873:26)
    at List.onClick (List.js:789:18)
```

**Comment by canonic-epicure** [comment] 2023-08-09 07:10
Silenced the exception in the `7235-infiniteScroll` branch. However it does not preserve the center date and investigation why goes too deep - will be better if someone in that context will check.

**Comment by canonic-epicure** [comment] 2023-08-10 10:31
It seems this is the duplicate of https://github.com/bryntum/support/issues/6994

**Comment by ExtAnimal** [comment] 2023-08-14 10:51
It is a dupe. Closing.

**Closed by ExtAnimal** 2023-08-14 10:51 UTC
Labels: bug, high-priority, forum, OEM
