### ISSUE TITLE
Event dates jumps when re-assign inline data

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7268] opened 2023-08-04 09:41 UTC
Use user app to reproduce. I was not able to reproduce with vanilla.
Video
https://github.com/bryntum/support/assets/7203098/baba23d4-08f8-441c-bcfa-0346e64863c2

App
[my-app.zip](https://github.com/bryntum/support/files/12259378/my-app.zip)

[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25681&p=128464#p128464)

**Comment by canonic-epicure** [comment] 2023-08-09 06:24
This issue happens because of the following:
1) The following events data is loaded:

        {
            id : "583",
            duration : 96,
            name : "t1",
            startDate : "2023-07-03T17:00:00.000",
            endDate : "2023-07-07T16:59:59.999",
            durationUnit : "hour",
            resourceId : "196",
        },
        {
            id : "584",
            duration : 96,
            name : "t2",
            startDate : "2023-07-10T17:00:00.000",
            endDate : "2023-07-13T16:59:59.999",
            durationUnit : "hour",
            resourceId : "196",
        }
2) Between these events there's a end-to-start dependency, so after loading, the start date of event 584 is moved to the "2023-07-07T17:00:00.000"
3) When a button is clicked the same events data is loaded (with the start date of event 584 as "2023-07-10T17:00:00.000")
4) For efficiency, when loading data, it is rendered as-is right away, and only then the scheduling logic is applied. So event 584 is first rendered at 2023-07-10 then dependencies logic moves it to 2023-07-07
5) To avoid this "visual jump" need to make sure the persisted data is saved already after the scheduling logic has been applied.

Closing this one as "works as intended", please feel free to open a new one with more information.

**Closed by canonic-epicure** 2023-08-09 06:24 UTC
Labels: bug, info requested, forum, large-account, works as intended
