### ISSUE TITLE
SlideToggle inside overflow menu triggers 2 change events 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8523] opened 2024-02-10 18:17 UTC
Reproducible in calendar-taskboard/ demo (remove overflow : null from kanban class)

Also note the widget stops functioning after being in the overflow menu, then back to toolbar

**Comment by dongryphon** [comment] 2024-03-23 16:36
This looks like a duplicate of https://github.com/bryntum/support/issues/8463

**Closed** 2024-04-26 10:05 UTC
Labels: bug, resolved
