### ISSUE TITLE
Child calendar ignores isWorking override if calendar data loaded remotely

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#2709] opened 2021-04-20 13:01 UTC
[child_calendar.json.zip](https://github.com/bryntum/support/files/6343716/child_calendar.json.zip)

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=17263&p=85681#p85681)

To reproduce,  use our examples and call in the console `scheduler.crudManager.loadCrudManagerData(json)`, there `json` - the data from the file attached.

Try to expand and move an event assigned to Bill to shaded area. It should be working time (check JSON data), but it doesn't.
![non_working](https://user-images.githubusercontent.com/7203098/115401051-a2c66280-a1f2-11eb-960c-165fa82027ea.gif)

It works great if same data has been applied as inline data using `calendarsData: []`
![working](https://user-images.githubusercontent.com/7203098/115401069-a823ad00-a1f2-11eb-98e2-76b8150b7693.gif)

Here is inline data code snippet:
```
 project: {
    calendarsData: [
      {
        id: "general",
        name: "24 hour calendar",
        intervals: [
          {
            startDate: "2021-04-20T00:00:00.000",
            endDate: "2021-04-21T00:00:00.000",
            isWorking: false
          },
          {
            startDate: "2021-04-17T00:00:00.000",
            endDate: "2021-04-19T00:00:00.000",
            isWorking: false
          }
        ],
        expanded: true,
        children: [
          {
            id: "business",
            name: "Business hours  (8am - 5pm)",
            intervals: [
              {
                recurrentStartDate: "every weekday at 12:00",
                recurrentEndDate: "every weekday at 13:00",
                isWorking: false
              },
              {
                recurrentStartDate: "every weekday at 17:00",
                recurrentEndDate: "every weekday at 08:00",
                isWorking: false
              }
            ]
          },
          {
            id: "nightshift",
            name: "Night shift (10pm - 6am)",
            intervals: [
              {
                recurrentStartDate: "every weekday at 6:00",
                recurrentEndDate: "every weekday at 22:00",
                isWorking: false
              }
            ]
          },
          {
            id: "exeptionalweekend",
            name: "Working W.E",
            intervals: [
              {
                startDate: "2021-04-17T00:00:00.000",
                endDate: "2021-04-19T00:00:00.000",
                isWorking: true
              }
            ]
          }
        ]
      }
    ],

    eventsData: [
      {
            id: 2,
            name: "Read docs",
            startDate: "2021-04-16T14:00:00",
            duration: 3,
            durationUnit: "h"
          },
          {
            id: 3,
            name: "Release docs",
            startDate: "2021-04-17T02:00:00",
            duration: 4,
            durationUnit: "h"
          }
    ],

    resourcesData: [
      {
        expanded: true,
        name: "ATELIER CERAMIQUE",
        leaf: false,
        id: "1abc1b60-35c9-4c80-9c02-929dec7f9a5b",
        children: [
          {
            id: 1,
            name: "Albert",
            calendar: "general",
            leaf: true
          },
          {
            id: 2,
            name: "Bill",
            calendar: "exeptionalweekend",
            leaf: true
          }
        ]
      }
    ],

    assignmentsData: [
      {
        event: 2,
        resource: 1
      },
      {
        event: 3,
        resource: 2
      }
    ],
    timeRangesData: [
      {
        startDate: "2021-04-17T00:00:00.000",
        endDate: "2021-04-19T00:00:00.000",
        name: "dead time"
      }
    ]
  },
```

**Comment by jsakalos** [comment] 2021-05-15 18:56
This is not a bug in fact because the inline data and loaded data is different. The main difference is that the loaded data contains:
```
project : {
    calendar : 'general'
    // ...
```
while inline data does not. Events have no calendar in both cases, only resources have. The result is that if no calendar is specified then project creates the default one with 24/7 working time. However, if the data is loaded then the `general` calendar is used and because the event does not have a calendar the project calendar is used. Project calendar has non-working weekend specified.

The solution is to set calendar also for the event when the logic starts to use intersection of resource and event calendars as described in https://bryntum.com/docs/scheduler-pro/#SchedulerPro/guides/basics/calendars.md#scheduling-logic-when-using-project%2C-event-and-resource-calenders

**Comment by jsakalos** [comment] 2021-05-17 07:53
According the discussion with Johan and Arcady, this is no issue. Closing.

**Closed by jsakalos** 2021-05-17 07:53 UTC
Labels: forum, high-priority, premium
