### ISSUE TITLE
Drag-drop exception in split demo

### ISSUE THREAD

**Issue by JockeLindberg** [bryntum/support#6970] opened 2023-06-09 12:39 UTC
Scheduler split demo:
1. Click both
2. Drag Task # 31 to bottom-left split window
3. Crash

[screen-capture (6).webm](https://github.com/bryntum/support/assets/100013589/0d7342fe-7f1f-4941-9daa-563197e030d9)

**Comment by isglass** [comment] 2023-06-09 13:48
Although not obvious, duplicate of #6958

**Closed by isglass** 2023-06-09 13:48 UTC
Labels: bug, bugbash
