### ISSUE TITLE
ExtJS modern demo: not possible to create more than one instance dynamically 

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#195] opened 2020-01-14 12:17 UTC
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=12591#p66188

To reproduce:
examples/extjsmodern/App/view/Main.js
```
/* eslint-disable */
Ext.define('App.view.Main', {
    extend : 'Ext.Panel',
    alias  : 'widget.main-view',

    layout : {
        type : 'hbox',
        align : 'stretch'
    },
    
    title  : 'Scheduler inside an ExtJS Modern Panel',
    id     : 'main-view',

    viewModel : {
        data : {
            rowHeight : 45
        }
    },

    tbar : {
        xtype   : 'button',
        text    : 'Add Scheduler',
        handler : function () {
            this.up().add({
                title : 'Bryntum Scheduler',
                xtype : 'schedulerpanel',
                flex  : 1,

                bind : {
                    rowHeight : '{rowHeight}'
                },

                eventStore : {
                    readUrl  : 'data/events.json',
                    autoLoad : true
                },

                resourceStore : {
                    readUrl  : 'data/resources.json',
                    autoLoad : true
                },

                columns : [
                    { text : 'Name', field : 'name', width : 130, locked : true }
                ],

                startDate  : new Date(2018, 3, 1, 6),
                endDate    : new Date(2018, 3, 1, 20),
                viewPreset : 'hourAndDay',

                eventRenderer : 'eventRenderer'
            });
        }
    },

    items : []
});
```

http://lh/scheduler/examples/extjsmodern/
1. Click "Add Scheduler"
2. See the scheduler is added
3. Click "Add Scheduler" again
4. See the exception:

```
SchedulerPanel.js?_dc=1573043177732:300 Uncaught TypeError: Cannot set property 'eventStore' of undefined
    at constructor.proto.<computed> [as setEventStore] (SchedulerPanel.js?_dc=1573043177732:300)
    at Ext.Configurator.configure (ext-modern-all.js:20)
    at constructor.initConfig (ext-modern-all.js:20)
    at constructor (ext-modern-all.js:20)
    at constructor (ext-modern-all.js:20)
    at constructor.callParent (ext-modern-all.js:20)
    at constructor (ext-modern-all.js:20)
    at constructor.callParent (ext-modern-all.js:20)
    at constructor (ext-modern-all.js:20)
    at new constructor (ext-modern-all.js:20)
```

**Comment by dongryphon** [comment] 2020-01-20 13:37
Slightly tweaked test case:
```
/* eslint-disable */
Ext.define('App.view.Main', {
    extend : 'Ext.Panel',
    alias  : 'widget.main-view',

    layout : {
        type : 'hbox',
        align : 'stretch'
    },

    title  : 'Scheduler inside an ExtJS Modern Panel',
    id     : 'main-view',

    viewModel : {
        data : {
            rowHeight : 45
        }
    },

    tbar : [{
        xtype   : 'button',
        text    : 'Add Scheduler',

        handler : function () {
            this.up('.main-view').add({
                title : 'Bryntum Scheduler',
                xtype : 'schedulerpanel',
                flex  : 1,

                bind : {
                    rowHeight : '{rowHeight}'
                },

                eventStore : {
                    readUrl  : 'data/events.json',
                    autoLoad : true
                },

                resourceStore : {
                    readUrl  : 'data/resources.json',
                    autoLoad : true
                },

                columns : [
                    { text : 'Name', field : 'name', width : 130, locked : true }
                ],

                startDate  : new Date(2018, 3, 1, 6),
                endDate    : new Date(2018, 3, 1, 20),
                viewPreset : 'hourAndDay',

                eventRenderer : 'eventRenderer'
            });
        }
    }, '->', {
        xtype    : 'spinnerfield',
        label    : 'Row height',
        width    : '12.5em',
        bind     : '{rowHeight}',
        minValue : 20
    }],

    items : []
});
```

**Comment by dongryphon** [comment] 2020-01-29 11:58
The issue is the `SchedulerPanel` wrapper are resolved by https://github.com/bryntum/bryntum-suite/pull/478 (mostly to do with mapping configs).

**Closed by dongryphon** 2020-01-29 11:58 UTC
Labels: bug, resolved
