### ISSUE TITLE
Crash in `shifted` demo in RTL

### ISSUE THREAD

**Issue by isglass** [bryntum/support#6706] opened 2023-05-05 09:20 UTC
Reproduction: 
```
StartTest(t => {
    document.body.style.direction = 'rtl';

    t.iit('Monkeys', async t => {
        await t.click('.b-day-name-date:contains(11-12)');
        await t.doubleClick('[data-event-id="2"]');
    });
});
```

**Comment by ExtAnimal** [comment] 2023-05-05 11:12
Duplicate of #6705

**Closed by ExtAnimal** 2023-05-05 11:12 UTC
Labels: bug
