### ISSUE TITLE
CalendarIntervalModel throws when calendar has been updated

### ISSUE THREAD

**Issue by simonihmig** [bryntum/support#5687] opened 2022-11-30 10:00 UTC
Unfortunately I wasn't able to extract a minimal reproduction. But the following does happen reliably (like not very deterministically, but still every now and then) in our app.

We pass data to our `SchedulerPro` instance as pojos (arrays of config objects), think of a typical schedulerpro-react like scenario (though we use Ember with a similar custom wrapper). This also includes calendar data, which is used for (resource-)non-working time. The non-working time does not actually update correctly, due to https://github.com/bryntum/support/issues/5602. But now an additional error pops up...

After updating calendars, whenever the scheduler needs to look at the data for calculating non-working time, for example when dragging events, or events have been removed from the view (scrolling, zooming) and are added back (again, not happening very deterministically, but it happens), the following error is thrown inside of some `CalendarIntervalModel`:

![image](https://user-images.githubusercontent.com/1325249/204758478-3f08f4d0-f4da-42d7-b222-b24bea0c073b.png)

This is at the following line of code:

![image](https://user-images.githubusercontent.com/1325249/204759273-7e4402a2-5d1a-4b52-b6b6-7615e470e10b.png)

Interesting: `this.stores` is an empty array, and the `isRemoving` flag is true. Without knowing the internals, but I would assume that a "removed" (disposed?) object is not supposed to be called anymore? And I would also assume that removing happens due to our calendar updates probably? 

The workaround we have in place is now specifically preventing calendar data from updating, which indeed "fixes" the problem. But I think that is still a bug that needs to be fixed.

**Comment by simonihmig** [comment] 2022-11-30 10:03
Oh, this is using `"@bryntum/schedulerpro` 5.2.0 btw

**Comment by canonic-epicure** [comment] 2022-11-30 10:27
Thank you for the report, we'll investigate. Can you elaborate on how exactly you pass the data to the Scheduler? Do you use CRUD manager or some API call?

**Comment by simonihmig** [comment] 2022-11-30 11:06
Well, I basically just set `instance.calendars = [...newData];`. This is happening in a very similar way to what `bryntum/schedulerpro-react` does in its `applyPropValue()` helper.

**Comment by canonic-epicure** [comment] 2022-11-30 11:53
Ok, thank you, I'll be investigating this one soon.

**Comment by canonic-epicure** [comment] 2022-12-01 08:36
Couldn't reproduce this issue in the latest code using the following scenario (based on your code for #5602):

```js
import '../_shared/shared.js'; // not required, our example styling etc.
import SchedulerPro from '../../lib/SchedulerPro/view/SchedulerPro.js';
import DateHelper from '../../lib/Core/helper/DateHelper.js';
import StringHelper from '../../lib/Core/helper/StringHelper.js';
import CSSHelper from '../../lib/Core/helper/CSSHelper.js';
import '../../lib/SchedulerPro/feature/ResourceNonWorkingTime.js';

CSSHelper.insertRule(
    '.weekend { background: transparent repeating-linear-gradient(-55deg, #dddddd99, #dddddd99 10px, #eeeeee99 5px, #eeeeee99 20px); }'
);
const wednesdayCalendar = {
    id                       : 'test',
    name                     : 'Wednesday',
    unspecifiedTimeIsWorking : false,
    intervals                : [
        {
            recurrentStartDate : 'on Wed at 0:00',
            recurrentEndDate   : 'on Fri at 0:00',
            isWorking          : true
        }
    ]
};
// const thursdayCalendar = {
//     id                       : 'test',
//     name                     : 'Thursday',
//     unspecifiedTimeIsWorking : false,
//     intervals                : [
//         {
//             recurrentStartDate : 'on Thu at 0:00',
//             recurrentEndDate   : 'on Fri at 0:00',
//             isWorking          : true
//         }
//     ]
// };

const baseCalendarsData = [
    {
        id                       : 'weekends',
        name                     : 'Weekends',
        unspecifiedTimeIsWorking : true,
        intervals                : [
            {
                recurrentStartDate : 'on Mon at 0:00',
                recurrentEndDate   : 'on Sat at 0:00',
                isWorking          : false,
                cls                : 'nonworking'
            }
        ]
    },
    {
        id                       : 'weekdays',
        name                     : 'Weekdays',
        unspecifiedTimeIsWorking : true,
        intervals                : [
            {
                recurrentStartDate : 'on Sat at 0:00',
                recurrentEndDate   : 'on Mon at 0:00',
                isWorking          : false,
                cls                : 'weekend'
            }
        ]
    }
];

const schedulerPro = new SchedulerPro({
    // appendTo : document.body,
    appendTo          : 'container',

    // makes scheduler as high as it needs to be to fit rows
    autoHeight : true,

    startDate : new Date(2022, 7, 2),
    endDate   : new Date(2022, 7, 14),

    columns : [
        { field : 'name', text : 'Name' },
        { field : 'calendar', text : 'Working on', editor : false }
    ],

    features : {
        nonWorkingTime         : true,
        resourceNonWorkingTime : {
            maxTimeAxisUnit : 'week'
        }
    },

    project : {
        resourcesData : [
            { id : 1, name : 'Bernard', calendar : 'weekends' },
            { id : 2, name : 'Bianca', calendar : 'weekdays' },
            { id : 3, name : 'Test', calendar : 'test' }
        ],

        calendarsData : [...baseCalendarsData, wednesdayCalendar]
    }
});

// let useWednesday = true;

setInterval(() => {
    schedulerPro.calendars = [
        ...baseCalendarsData, wednesdayCalendar
        // useWednesday ? wednesdayCalendar : thursdayCalendar
    ];
    // useWednesday = !useWednesday;
}, 1000);
```

So it might be fixed in the latest release already or I'm missing something. Please provide more detailed steps to reproduce.

**Comment by canonic-epicure** [comment] 2022-12-06 07:31
We'll be working on this issue, right now found another exception in this test case.

**Comment by canonic-epicure** [comment] 2022-12-26 11:08
An error with the very similar stack trace has been fixed just recently: https://github.com/bryntum/support/issues/5718 perhaps it also fixes this issue. Please try to reproduce it in the next release (5.2.6)

**Comment by canonic-epicure** [comment] 2023-02-10 06:59
Closing this one as unactionable at the moment. @simonihmig Please feel free to open a new ticket with more detail information.

**Closed by canonic-epicure** 2023-02-10 06:59 UTC
Labels: bug, info requested
