### ISSUE TITLE
CrudManager guide should cover events/resources in Calendar + Scheduler

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#8907] opened 2024-03-28 07:49 UTC
https://bryntum.com/products/calendar/docs/guide/Calendar/data/crud_manager

https://bryntum.com/products/scheduler/docs/guide/Scheduler/data/crud_manager

**Comment by isglass** [comment] 2024-04-06 14:56
Duplicate of https://github.com/bryntum/support/issues/8524, which has already been fixed

**Closed by isglass** 2024-04-06 14:56 UTC
Labels: duplicate, docs, onboarding
