### ISSUE TITLE
Rapidly drag creation generates an error

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7184] opened 2023-07-19 03:51 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25654&p=127608#p127608)

go here: https://bryntum.com/products/schedulerpro/examples/percent-done/

Then go to an empty row. Drag to create an item and when done quickly (very quickly) move mouse down the page a bit. You will get:;

```
Uncaught (in promise) DOMException: Failed to execute 'appendChild' on 'Node': The node to be removed is no longer a child of this node. Perhaps it was moved in a 'blur' event handler?
    at Tooltip.toFront (https://bryntum.com/products/schedulerpro/build/schedulerpro.module.js?469230:10:645562)
    at Tooltip.afterShowByTarget (https://bryntum.com/products/schedulerpro/build/schedulerpro.module.js?469230:10:993806)
    at Tooltip.handleForElementOver (https://bryntum.com/products/schedulerpro/build/schedulerpro.module.js?469230:10:990732)
    at Tooltip.internalOnPointerOver (https://bryntum.com/products/schedulerpro/build/schedulerpro.module.js?469230:10:989319)
    at HTMLDivElement.o (https://bryntum.com/products/schedulerpro/build/schedulerpro.module.js?469230:10:181689)
```

https://github.com/bryntum/support/assets/75997756/22572ef4-2000-4bbf-af0d-2957ea215512

**Comment by isglass** [comment] 2023-07-20 06:58
Duplicate of bryntum/support#7091

**Closed by isglass** 2023-07-20 06:58 UTC
Labels: bug, duplicate, high-priority, in progress, forum
