### ISSUE TITLE
Non working days not painted after adding a calendar interval programmatically

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#5394] opened 2022-10-11 12:10 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=21790&p=111704#p111704)

```
gantt.project.calendar.addIntervals([
  {
    recurrentStartDate: 'on Tue at 0:00',
    recurrentEndDate: 'on Wed at 0:00',
    isWorking: false,
  }
]);
```

No update in UI, but seen if you call gantt.zoomIn()

Should be fixed for: `ResourceNonWorkingTime`, `TaskNonWorkingTime`, `NonWorkingTime`, `EventNonWorkingTime`

**Comment by canonic-epicure** [comment] 2022-12-09 09:54
Set as "Blocking" as part of #5718 (which is "blocking")

**Comment by schTi** [comment] 2022-12-20 14:40
@canonic-epicure Hi, can you please tell me if this ticket will also fix the bug reported [here](https://forum.bryntum.com/viewtopic.php?t=23234) (TL;DR: That events are not rescheduled, when the dynamically added non-working interval overlaps a dependency lag (not the event directly)). I was told it will be fixed with the next release, and just wanted to subscribe to the progress. If not, can you point me to the correct ticket? Thanks. If it is [this](https://github.com/bryntum/support/issues/2176) one, then please try to reproduce again with the configuration of my initial forum post from above.

**Comment by canonic-epicure** [comment] 2022-12-20 14:47
Hi, no, this one is only about UI update and the #2176 seems to be about incorrect scheduling (on data level). 

But it most probably will be fixed for nearest release too, while I'm in calendars context. Yes, please track https://github.com/bryntum/support/issues/2176 for the progress (and you can post the repro instructions there, right now its a bit all over the place).

**Comment by canonic-epicure** [comment] 2022-12-22 08:56
Fixed for `TaskNonWorkingTime`

**Comment by canonic-epicure** [comment] 2022-12-22 12:10
Fixed for `ResourceNonWorkingTime`

**Comment by canonic-epicure** [comment] 2022-12-22 14:08
`EventNonWorkingTime` seems to be ok, added tests

**Comment by canonic-epicure** [comment] 2022-12-23 08:42
Fixed for `NonWorkingTime`

**Closed** 2022-12-28 10:37 UTC
Labels: bug, resolved, high-priority, forum, large-account, OEM
