### ISSUE TITLE
Delete task takes a while when big dataset used

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#6099] opened 2023-02-02 11:55 UTC
Test data attached.
In advanced demo:
```
    project : {
        // Let the Project know we want to use our own Task model with custom fields / methods
        taskModelClass : Task,
        autoLoad  : true,
        taskStore : {
            readUrl : 'testData.json',
            autoLoad : true
            // wbsMode : 'auto'
        },
        dependencyStore : {
            readUrl : 'dependencies.json',
            autoLoad : true
        },
```

https://user-images.githubusercontent.com/7203098/216317763-e5e8ca92-02ac-4d27-bec3-908dd866bcb2.mov

[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=23736&p=117641#p117641)

we do have around 20000 tasks with around 20 root tasks (the others somehow children). When we delete on root object having not any children via applyChangeset, changes.removed it takes even on brand new M1 MacBook around 40 seconds until the gantt is usable (no sorters applied ...).

The same if we do an interactive delete with your standard delete context option

[jsons.zip](https://github.com/bryntum/support/files/10568631/jsons.zip)

**Comment by chuckn0rris** [comment] 2023-02-03 11:13
User added: 
>by the way the same situation is with adding an object

**Comment by marciogurka** [comment] 2023-02-03 14:20
[User asking for priority](https://forum.bryntum.com/viewtopic.php?p=117753#p117753)

**Comment by canonic-epicure** [comment] 2023-03-17 06:46
It is probably a duplicate of #6262

**Comment by canonic-epicure** [comment] 2023-04-10 13:19
Seems not, its caused by the excessive "marking as dirty" - every task removal (for every child) triggers the marking of the big part of graph as "dirty".

**Closed** 2023-05-26 08:00 UTC
Labels: bug, resolved, premium, forum, large-account, OEM
