### ISSUE TITLE
Should be possible to define more than one default value for combo with multi select in FilterBar

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2993] opened 2021-06-07 11:52 UTC
https://www.bryntum.com/forum/viewtopic.php?f=43&t=17722&p=87771#p87771

<img width="1085" alt="Снимок экрана 2021-06-07 в 14 50 08" src="https://user-images.githubusercontent.com/57486733/121011778-ac565a80-c79f-11eb-8303-74d516882907.png">

For now need to duplicate values and filter function:
Grid/examples/filterbar/app.js
```
    features : {
        filterBar : {
            compactMode : false,
            filter      : {
                property : 'city',
                value    : ['Paris', 'Barcelona'],
                filterBy(record) {
                    return !this.value.length || this.value.includes(record.city);
                }
            }
        },
.......
    columns : [
        {
            text       : 'City',
            field      : 'city',
            flex       : 1,
            editor     : cityCombo,
            filterable : {
                // filterField : cityCombo,
                filterField : Object.assign(cityCombo, {
                    value : ['Paris', 'Barcelona']
                }),
                filterFn : ({ record, value }) => !value.length || value.includes(record.city)
            }
```

**Comment by matsbryntse** [comment] 2021-08-29 21:29
Dupe of #3344 2951

**Closed by matsbryntse** 2021-08-29 21:29 UTC
Labels: bug, premium, forum
