### ISSUE TITLE
Hidden filter bar appears on column hide

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#522] opened 2020-04-08 13:01 UTC
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=51&t=13707

Steps:

1. add `filterBar:true` to `features` in `Scheduler/examples/grouping/app.js`
2. mimic the attached screencast:

(Note: There are no console errors)

![filer-bar-bug](https://user-images.githubusercontent.com/204844/78786776-98e80d80-79a9-11ea-9ea4-bb0274663a70.gif)

**Comment by matsbryntse** [comment] 2020-05-21 07:08
Dupe of Fixed #521

**Closed by matsbryntse** 2020-05-21 07:08 UTC
Labels: bug
