### ISSUE TITLE
Flaky locked grid row hover effect when moving mouse over task labels

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#377] opened 2020-02-29 21:48 UTC
https://bigfiles.assembla.com/spaces/cHlz5-LZyr4kUleJe5cbCb/documents/download/dJNV8MuYGr6zTZcK-zJOy8

**Comment by isglass** [comment] 2023-10-19 08:54
We no longer use grid row hover effect when hovering schedule, but keeping ticket since the background of the row number column blinks when moving mouse over tasks / rows

**Comment by isglass** [comment] 2024-05-08 12:39
And that is not longer reproducible either, closing

**Closed by isglass** 2024-05-08 12:39 UTC
Labels: bug, low-priority, not reproducible
