### ISSUE TITLE
showCurrentTimeline isn't working when setting name in Timeline widget

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9461] opened 2024-06-28 10:51 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=29546&p=149417#p149417)

Reproduction screenshot -->
![timeline_timeranges_issue_2024-06-28_11-28-23](https://github.com/bryntum/support/assets/75997756/b66898bc-a104-48e3-8391-6240a77a3f1f)

Reproducible demo link https://bryntum.com/products/gantt/examples/timeline/

**Comment by ghulamghousdev** [comment] 2024-06-29 11:24
Duplicate of this: https://github.com/bryntum/support/issues/8970

**Closed** 2024-07-05 08:06 UTC
Labels: bug, regression, resolved, forum, OEM
