### ISSUE TITLE
Snap to zoom timespan

### ISSUE THREAD

**Issue by jashworth** [bryntum/support#2849] opened 2021-05-08 14:39 UTC
Gantt / 4.1.2

Zooming to a preset sets the timespan.

```typescript
instance.zoomTo('my-preset');
// timeAxisChange 27.293 27.431
```

After zooming out one level, and then zooming in one level, the timespan no longer matches the initial value.

```typescript
// zoom ➖ (ctrl+mousewheel)
// timeAxisChange 24.600 30.117

// zoom ➕ (ctrl+mousewheel)
// timeAxisChange 27.000 27.721 // different from initial
```

It's like taking one step back and one step forward and ending up in a slightly different place.

Is there a way to "snap" the initial timespan to be the same as the final timespan (the timespan that the last zoom "snaps" to) to avoid this effect?

**Comment by chuckn0rris** [comment] 2021-09-02 08:23
After investigation I was not able to reproduce the issue when the zoomLevel is a decimal value. This moment looks like fixed. 
About the zoomIn/zoomOut action I've found the next: When a user specify viewPreset with its widths, he can also set startDate and endDate for the timeAxis. In case they are close and timeAxis is wide enough, a scroll won't be appeared, but tick width will be increase accordingly to fit all visible area of the timeAxis. After user zoomIn/zoomOut, start/end dates will be automatically recalculated depends on may factors - timeAxis width, events data, etc; so scroll will be appeared and after user do zoom back, start/end date won't be replaced to initial values, but zoom level will be restored correctly. Ticks width may not be the same as after initial load (because they might be extended to fit the space), but will have sizes that user specified in his viewPreset settings. This is expected behaviour.

I will close this ticket with "cannot reproduce" resolution.

**Closed** 2021-09-02 08:23 UTC
Labels: bug, not reproducible, forum
