### ISSUE TITLE
[VueJS] [Calendar] Modes selector dropdown default.

### ISSUE THREAD

**Issue by dcruz1990** [bryntum/support#5845] opened 2022-12-28 15:19 UTC
Hi, i recently upgrade to 5.2.5 and I'm just trying to remove this:

![image](https://user-images.githubusercontent.com/43586145/209833240-6ea9f01d-9946-4734-96a4-d9e3597e9c55.png)

The result is that when Calendar first render it renders the drop-down, but when i make a change in the code and hot reload occurs, it renders like this:
![image](https://user-images.githubusercontent.com/43586145/209833570-fe181976-5ea1-48ca-9a0b-ae8cdf6d1441.png)

Which is the way i want it to render. 

Any idea?

**Comment by taauntik** [comment] 2022-12-29 07:53
Hi @dcruz1990,

I tried to reproduce it with our VUE example, It works fine for me. Could you please provide the steps to reproduce it? The debugging process would be much simpler and faster if you could provide a runnable test case, where we can reproduce it.

**Comment by dcruz1990** [comment] 2022-12-29 14:04
But, how can i just disable that dropdown? there is an option for that?

**Comment by ExtAnimal** [comment] 2022-12-29 14:19
The dropdown is not visible by default. This is why we need some help.

**Comment by dcruz1990** [comment] 2022-12-29 14:27
Where in the documentation i can find info about how to show that dropdown? if it isn't visible by default then somewhere in the docs would be an explanation on how to turn on right?

**Comment by ExtAnimal** [comment] 2022-12-29 15:00
It is shown when you click the mode selector when the Calendar is narrow and the mode buttons cannot be shown. This is *all* automatic. If it shows, then something is wrong and we need to see the app to reproduce it.

![modeselector](https://user-images.githubusercontent.com/200516/209971115-1a8bff71-abd6-49ab-9864-7b02ffb92e43.gif)

**Comment by ExtAnimal** [comment] 2022-12-29 16:20
So, shall I close this ticket?

**Comment by dcruz1990** [comment] 2022-12-29 17:06
Yeah close it, I'll figure it out anyway.

**Closed** 2022-12-29 17:07 UTC

**Comment by matsbryntse** [comment] 2022-12-29 21:23
@dcruz1990 Please post here if you're not able to figure out what's going on and we'll do our best to help!

**Comment by dcruz1990** [comment] 2022-12-29 21:46
So far i wasn't able to fix it, but i have a clue, when calendar first renders, it behaves like it doesn't have enough space to render all the modes and the extra buttons, so it goes to default and shows the dropdown selector, but if i, for example, change some values on the modes prop, (without removing a mode, just turning to null a year for ex)  when hot reload finish it re-render normally (doesn't show the dropdown). That is all i know and i can't provide you with a reproducible example right now. 

Thank you so much for being interested on this and for Calendar & Grid, such a great and helpful products.

**Comment by ExtAnimal** [comment] 2022-12-30 10:05
So the issue is why it finds that the width is too small to render the separate buttons and flips to using the single button with a Menu.

How is the Calendar being created? Into what element is it being rendered, and how does that containing element size its child elements?

For example does it have the styles

```
display : flex;
align-items : stretch;
```

Widgets use `flex : 1 1 auto` by default, so if the encapsulating element is `display : flex`, it will take up the full width of that element.

The `align-items: stretch` should mean that the Calendar occupies the full height of the containing element (Assuming that the default of `flex-direction : row` is being used.

And is this containing element also sized correctly by CSS? Layout has to be defined all the way down from the viewport.
