### ISSUE TITLE
Clicking header of framework demos gives inconsistent results

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#1161] opened 2020-07-10 10:08 UTC
https://www.bryntum.com/examples/scheduler-pro/angular/angular-8/dist/angular-8/index.html

Click demo header

**Comment by jsakalos** [comment] 2020-07-31 08:40
The problem is broader than one-demo issue. Clicking the header link gives inconsistent results: some point to the example itself with './' which reloads the page, some point to themselves with '#' which does nothing, some Angular demos give 404.

Make the link consistently point to the example browser of each product (Grid, Scheduler, SchedulerPro, Gantt, Calendar) and each framework (Angular [all versions], React, Vue). Mind please that examples in `SchedulerPro/examples-scheduler` are copied from the normal Scheduler.

**Comment by fabiojpoli** [comment] 2020-09-17 18:55
@SergeyMaltsev , as discussed, I realize that you worked on similar (maybe duplicated) issue about this problem (https://github.com/bryntum/support/issues/1510) that was just merged today.

I was to test all to confirm that your fix will also fix this issue but I have to build  (configure .net, etc) every example to test on my local. As you worked on it do you have all the demos built on your local to test and resolve this issue?

Thank you, I appreciate.

**Comment by fabiojpoli** [comment] 2020-09-25 23:04
Hi @SergeyMaltsev , as you are working on this issue, could you please fix this items and then close this issue?

I checked all demos on my local clicking on header link.

On all examples page, when click on header it anchor to ##example-examples and nothing happens. Is it a correct behaviour?

http://lh/master/bryntum-suite/Calendar/examples/
http://lh/master/bryntum-suite/Gantt/examples/
http://lh/master/bryntum-suite/Grid/examples/
http://lh/master/bryntum-suite/Scheduler/examples/
http://lh/master/bryntum-suite/SchedulerPro/examples/

Clicking on these examples header, it back but doesn't put border on thumb (mark as selected)
http://lh/master/bryntum-suite/Scheduler/examples/angular/pdf-export/dist/pdf-export/index.html
http://lh/master/bryntum-suite/Scheduler/examples/vue/javascript/pdf-export/dist/index.html
http://lh/master/bryntum-suite/SchedulerPro/examples/frameworks/custom-build/
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/custom-build/
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/angular/pdf-export/dist/pdf-export/index.html
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/vue/javascript/pdf-export/dist/index.html
http://lh/master/bryntum-suite/Scheduler/examples/custom-build/

Click on these examples header, the route just change to `#` and doesn't back to examples page:
http://lh/master/bryntum-suite/Scheduler/examples/react/javascript/pdf-export/build/index.html
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/react/javascript/pdf-export/build/index.html

This example doesn't have a header link to back to examples page:
http://lh/master/bryntum-suite/Scheduler/examples/vue/javascript/vuestic/dist/index.html#/admin/dashboard
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/vue/javascript/vuestic/dist/index.html
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/extjsmodern/

These examples I was unable to build on local to check:
http://lh/master/bryntum-suite/Calendar/examples/frameworks/react/javascript/filtering/build/index.html
http://lh/master/bryntum-suite/Grid/examples/salesforce/
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/salesforce/
http://lh/master/bryntum-suite/Scheduler/examples/angular/angular-2/
http://lh/master/bryntum-suite/Scheduler/examples/react/typescript/basic/build/index.html
http://lh/master/bryntum-suite/Scheduler/examples/react/typescript/recurring-events/build/index.html
http://lh/master/bryntum-suite/Scheduler/examples/salesforce/
http://lh/master/bryntum-suite/SchedulerPro/examples/frameworks/angular/resource-histogram
http://lh/master/bryntum-suite/Calendar/examples/frameworks/react/javascript/filtering/build/index.html
http://lh/master/bryntum-suite/Scheduler/examples/aspnet/
http://lh/master/bryntum-suite/Scheduler/examples/aspnetcore/
http://lh/master/bryntum-suite/SchedulerPro/examples/frameworks/angular/resource-histogram/dist/resource-histogram/index.html
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/angular/angular-2/
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/angular/angular-5/dist/index.html
http://lh/master/bryntum-suite/SchedulerPro/examples/frameworks/react/javascript/resource-histogram/build/index.html
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/react/typescript/basic/build/index.html
http://lh/master/bryntum-suite/SchedulerPro/examples-scheduler/react/typescript/recurring-events/build/index.html

**Closed** 2020-10-20 07:55 UTC
Labels: angular, bug, example, in progress, react, resolved, vue
