### ISSUE TITLE
Export filed if filter Format combo in Export dialog

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#10509] opened 2024-12-17 15:11 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=31375&p=160075#p160075)

Reproduced here https://bryntum.com/products/grid/examples/export/
Apply to export feature 
```
        pdfExport : {
            exportDialog: {
                items: {
                    paperFormatField: {
                        store: {
                            filters: [
                            {
                                operator: "isIncludedIn",
                                property: "id",
                                value: ["A3", "A4"],
                            },
                            ],
                        },
                    }, 
                },
            },
            exportServer: 'https://dev.bryntum.com:8082',
            // Required for font-awesome icons to display correctly
            
            headerTpl,
            footerTpl
        }
```

Select any available format and click Export. See "Export filed" notification. No errors in console.

**Comment by ExtAnimal** [comment] 2024-12-17 15:22
Dupe of https://github.com/bryntum/support/issues/10510

**Closed by ExtAnimal** 2024-12-17 15:22 UTC
Labels: bug, premium, pdf export, forum, large-account, OEM
