### ISSUE TITLE
Angular: RC-1 demo failures

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#1593] opened 2020-09-29 10:35 UTC
## Grid

- [x] angular\angular-1 (Runtime. Doesn't work in IE11)

- [x] angular\angular-renderer (Runtime. FullScreen in IE11 doesn't work as expected)

- [ ] angular\angular-7 (Build. `"buildOptimizer": true`)
- [x] angular\angular-renderer (Build. `"buildOptimizer": true`)
Angular application with `"buildOptimizer": true` reveals some problems.
Resolved yet with setting `"buildOptimizer": false` for production build `--prod`
```
TypeError: Cannot use 'in' operator to search for 'b-grid-1-columns' in undefined
```

## Scheduler

- [x] angular\drag-between-schedulers (doesn't work with `--prod` mode)
```
VM24 main.eb55a6116d26db4dcc3d.js:1 TypeError: Cannot read property 'some' of undefined
    at o.value (VM24 main.eb55a6116d26db4dcc3d.js:1)
```

##  Calendar

- [x] `Widget class x with no $$name getter found` console warning. I occurred also in other products and tracing it down led to basic classes `Calendar`, `Scheduler`, etc. 

## IE11

Almost all demos may throw this at runtime
```
SCRIPT5011: Can't execute code from a freed script
SCRIPT5007: Unable to get property 'shadowRoot' of undefined or null reference
```

**Comment by jsakalos** [comment] 2020-09-30 15:14
Double compile is caused by the combination of:

1. `enableIvy:true`
2. our packages installed from filesystem

I have solved it for now by setting `enableIvy:false`. It will become irrelevant when we will use Bryntum NPM packages installed from our server.

**Comment by SergeyMaltsev** [comment] 2020-10-06 12:02
Possible workaround for 
```
SCRIPT5011: Can't execute code from a freed script
```
Add this to index.html or to tests
```
<script nomodule>window.__Zone_enable_cross_context_check = true;</script>
```

**Comment by jsakalos** [comment] 2020-10-06 18:28
Calendar issue will be fixed when https://github.com/bryntum/bryntum-suite/pull/2177 will be merged

**Comment by SergeyMaltsev** [comment] 2020-11-20 05:56
All issues have been resolved.

**Closed** 2020-11-20 05:57 UTC
Labels: angular, bug, bugbash, example, resolved
