### ISSUE TITLE
Add SchedulerPro wrappers to Gantt frameworks NPMs and create gantt-schedulerpro demos for frameworks

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#2970] opened 2021-06-02 14:45 UTC
The (temporary) solution will be to include SchedulerPro wrappers into Gantt bundle. Then the user will use only one npm package, gantt, and will import all necessary Bryntum components from it. The solution consists of:

- [x] include SchedulerPro and SchedulerProBase wrappers in Gantt
- [x] create Angular gantt-schedulerpro demo 
- [x] create React gantt-schedulerpro demo 
- [x] create Vue gantt-schedulerpro demo 
- [x] create Vue-3 gantt-schedulerpro demo 

----------------------------------

Reproduced with the user code.

It works in vanilla (schedulerpro + gantt) when setting partner from console but does not work in the user's React example.

https://www.bryntum.com/forum/viewtopic.php?f=44&t=17672&p=87572#p87572
https://www.bryntum.com/forum/viewtopic.php?p=88248#p88248

Hi,
I am using gantt and scheduler. On giving partner between gantt and scheduler I am getting this error. 
![Capture.PNG](https://www.bryntum.com/forum/download/file.php?id=13412)
I have attached the test case. Please let me know where to make corrections
![Capture.PNG](https://www.bryntum.com/forum/download/file.php?id=13412)

**Comment by isglass** [comment] 2021-06-14 05:33
Bundles will be reworked for 5.0.

**Comment by pmiklashevich** [comment] 2021-06-15 11:05
Looks like this is a duplicate of https://github.com/bryntum/support/issues/1517

**Closed** 2021-06-30 10:02 UTC
Labels: angular, bug, example, forum, react, ready for review, resolved, vue, vue3
