### ISSUE TITLE
Support showing events in a different timezone

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#1533] opened 2020-09-17 12:30 UTC
Originally reported here: https://app.assembla.com/spaces/bryntum/tickets/9432-add-time-zone-support/details

Forums:
https://www.bryntum.com/forum/viewtopic.php?f=51&t=12553
https://www.bryntum.com/forum/viewtopic.php?f=52&t=16081
https://www.bryntum.com/forum/viewtopic.php?f=51&t=19298&p=95404#p95404
https://www.bryntum.com/forum/viewtopic.php?f=51&t=20340&p=100967#p100967
https://www.bryntum.com/forum/viewtopic.php?f=44&t=21512&p=106402#p106402

**Comment by matsbryntse** [comment] 2020-09-17 15:08
Dupe of #1407

**Comment by pmiklashevich** [comment] 2020-12-02 18:18
POC: Scheduler/examples/crudmanager/app.js
```
const localTimezoneOffset = new Date().getTimezoneOffset();

class TimeZoneScheduler extends Scheduler {
    static get $name() {
        return 'TimeZoneScheduler';
    }

    static get type() {
        return 'timeZoneScheduler';
    }

    static get configurable() {
        return {
            // https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset
            currentTimeZoneOffset : null,

            currentTimeZoneName : ''
        };
    }

    updateCurrentTimeZoneOffset(value, was) {
        const offset = -1 * value / 60;
        this.currentTimeZoneName = (offset > 0 ? '+' : '') + offset + 'h';

        if (was == null) return;

        const shiftBy = -1 * (value - was);

        this.eventStore.beginBatch();
        this.eventStore.forEachScheduledEvent(event => {
            event.shift('minute', shiftBy);
        });
        this.eventStore.endBatch();
    }
}

// Register this widget type with its Factory
TimeZoneScheduler.initClass();

const scheduler = new TimeZoneScheduler({
    currentTimeZoneOffset : localTimezoneOffset,

    eventRenderer({ eventRecord }) {
        return `${eventRecord.name} (${scheduler.currentTimeZoneName})`;
    },
.....
    crudManager : {
        listeners : {
            beforeSync({ pack }) {
                pack.offset = scheduler.currentTimeZoneOffset;
            }
        },
....
    tbar : [
....
        {
            type      : 'slider',
            ref       : 'timezonePicker',
            text      : 'Timezone offset',
            width     : 400,
            step      : 60,
            min       : -240,
            max       : 240,
            value     : localTimezoneOffset,
            listeners : {
                change({ value, userAction }) {
                    if (userAction) {
                        scheduler.currentTimeZoneOffset = value;
                    }
                }
            }
        }
    ]
});
```

**Comment by pmiklashevich** [comment] 2020-12-02 18:19
The idea is to introduce an offset property. You need to sync it between the server and client side. If you store the data in a specific timezone, let's say UTC, and you know the offset property, it's easy to transform all dates. So, for example,

- you store dates in UTC in database
- you check out data and convert it according to the offset property to the local time
- return local time and offset to the client side
- since dates are in local format (there is no "Z" in the strings), the are applied the way they specified
- you changed the offset in the client and shift the tasks accordingly
- you save the data and apply the new offset from client side as extra param in the query
- on server you convert the dates to UTC time based on the offset you received

![Запись активности на экране 2020-12-02 в 20 56 01](https://user-images.githubusercontent.com/57486733/100914273-e6d6f600-34e3-11eb-9fdb-16064105b2d9.gif)

**Comment by bmblb** [comment] 2021-01-28 08:26
> We're using this library to "switch" our app with Scheduler into UTC mode, where there is no DST: https://www.npmjs.com/package/utc-date-class
> Switching to other time zones is a bit more complicated, since you have to have a database with all DST changes and render the header according to that... so I also looking forward to this built-in feature!

**Comment by lukasz-bendykowski-fluke** [comment] 2022-02-02 11:15
Hi guys! 

Our company have recently switched to Bryntum for scheduling and calendar functionality. We provide our solution to many big clients worldwide and the proper time zone handling is crucial for us. Just need to clarify the exact direction of the work here.

We show data to our clients in the time zone selected for the specific "site" they access, not the user computer's time zone. As I'm responsible for implementing the scheduler I have partially worked around that limitation. The native implementation of time zone selection would be really appreciated though.

We store all the events in the DB in UTC, with the information about the time zone is stored in the "site". We convert dates to the proper time zone just before displaying them to the end-user working internally using UTC. With our previous solution, we have moved from, we could set the time zone that we want to use in the scheduler and just feed it with the proper data including dates ISO formatted for that time zone.

Can you describe the solution you work on here?
What and how exactly will be affected?
Will the current time indicator be displayed correctly for the chosen time zone?
As `startDate` and `endDate` can be of `Date` type that doesn't provide time zone information, will you be able to show events properly for the time zone provided?

Thanks a lot for your input here and for the great product!

**Comment by bmblb** [comment] 2022-02-02 13:36
Hello.
We're working on implementation similar to ExtScheduler. Please refer to this demo: https://www.bryntum.com/examples/scheduler-for-extjs/timezones/

This is a simple implementation that doesn't know anything about DST in various time zones. We do not tamper with dates on the data level, we only change the way dates are displayed in UI. For instance, if system in UTC+3 and scheduler is configured to show UTC+1, we take date to display and subtract 2 hours to feed this date to our date formatters which rely on native getDate(), getMonth() etc.
There are thoughts to make API customizable enough to allow using 3rd party libraries (like momentjs) to convert date to real timezone with real DST. Timezone information is about 500kb uncompressed which is why we don't want to include it by default.

> As startDate and endDate can be of Date type that doesn't provide time zone information, will you be able to show events properly for the time zone provided?

We rely on browser implementation of the Date. If you're loading date without timezone info it will be interpreted as local time:
```
// assuming I'm in UTC+3
> new Date('2020-01-01T12:00').toUTCString()
'Wed, 01 Jan 2020 09:00:00 GMT'

> new Date('2020-01-01T12:00z').toUTCString()
'Wed, 01 Jan 2020 12:00:00 GMT'
```
We are not going to modify dates on the data level. You can do it on application level if needed, but I'd just always provide timezone info. In your case it is 'z' symbol at the end of the date string, meaning date is in UTC.

**Comment by bsz23** [comment] 2022-09-19 08:16
Hi, 
@bmblb @matsbryntse @SergeyMaltsev Is it possible to share with us the estimated release date of this long-awaited feature?  
Thank you.

**Comment by dkornel** [comment] 2022-10-10 10:39
Hi all,

could you please share with us the estimated release date of timezone support ? how likely timezones are going to land in 5.2.x ?

Kornel

**Comment by marciogurka** [comment] 2022-10-19 19:36
[+1](https://www.bryntum.com/forum/viewtopic.php?p=112140#p112140) user asking here

**Comment by vstrichenko** [comment] 2022-11-16 11:51
Hello, could you please update on status for this feature request.

**Comment by isglass** [comment] 2022-12-21 12:54
Hi @dkornel,

We are behind schedule, but hope to have an alpha out this week

**Closed** 2022-12-23 10:01 UTC
Labels: feature request, resolved, high-priority, premium

**Comment by dkornel** [comment] 2023-01-03 20:57
Hi @isglass ,

I have installed angular scheduler pro 5.3.0-beta-1 and give it a shot. I noticed that Events are rendered based on local dates for the first time. When I click on the event, they are being converted to configured time zone iana. Are you aware of it ?

Best regards,
Kornel

**Comment by strichenko** [comment] 2023-01-12 10:15
Hey,  guys, I was also testing beta build. And I have a question to the current feature. 

Is it possible configure schedule to use only utc time which do not have dst missing hours.
I am trying to find a way to show all hours in  the header no matter what date is selected, 
Currently 3 am is missing due to dst convertion even if I  provide itc timezone in configuration. Maybe I am missing something.
<img width="1530" alt="Screenshot 2023-01-12 at 12 07 26" src="https://user-images.githubusercontent.com/48662556/212039882-c3a337ee-29b2-4b01-a8a7-602914e5f501.png">

**Comment by lurivera** [comment] 2023-01-17 16:49
Any updates on this feature or an expected date for when this is going to be ready for production use? @SergeyMaltsev @matsbryntse This is an important feature for us and will significantly change our implementation plan if we can't count on this to be available

**Comment by JockeLindberg** [comment] 2023-01-19 08:48
@dkornel I think that it was you who reported this in the forums as well, https://github.com/bryntum/support/issues/5889. Will be fixed in 5.3.0-beta-2.

**Comment by JockeLindberg** [comment] 2023-01-19 09:02
@strichenko I'm afraid that currently we are stuck with those DST switch issues, as the timeline is calculated in local system time zone.

Our plan was to implement time zone support that works good enough while waiting for the Temporal API to become available. And then to implement full time zone support using the Temporal API.

**Comment by JockeLindberg** [comment] 2023-01-19 09:05
@lurivera We plan to release 5.3.0-beta-2 during next week and if all goes well, the public 5.3.0 shortly after that.

**Comment by zamber** [comment] 2023-02-13 10:18
Hi @JockeLindberg, when can we expect public 5.3.0? I'm testing beta2 rn, are there any issues with it I should be wary of?

**Comment by JockeLindberg** [comment] 2023-02-13 10:30
@zamber We are currently preparing for the release. Will do some manual testing before, and if that is ok, then it will probably be out next week. As far as I know, there is no open issue regarding time zone functionality.
