### ISSUE TITLE
Gantt - Copy and Paste Node - order of records in 'add' event of task store is inconsistent

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4036] opened 2022-01-17 21:06 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=20028&p=99335#p99335)

Hi,

I have created 2 nodes A, B. B is a child of A.
-A
   B

If you copy and past these two nodes the order of the nodes within the records array of the add event is dependent on the selection order of the user. 

```
gantt.project.taskStore.on({
   add: ({ records } ) => {
          // records[0] if you select B first here is A and vice versa
         }
   });

```

Is this correct behaviour? I think the inserted nodes should be ordered in a different way, e.g. with the sequenceNumber, parents always first.

If you observe the records array within an expand operation it think it is order this way.

Many Thanks,
Peter

**Comment by JockeLindberg** [comment] 2023-11-13 08:16
Can't reproduce in the current version. Closing. If it's still a problem, we can reopen it.

**Closed by JockeLindberg** 2023-11-13 08:16 UTC
Labels: bug, forum
