### ISSUE TITLE
Event cannot be dropped between pro schedulers

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3688] opened 2021-11-09 06:49 UTC
Here is a simple test case. Run it, try to manually dragdrop event between schedulers, see exception in console

```
t.iit('Should drop event between schedulers', async t => {
        const scheduler = await t.getSchedulerProAsync({
            enableEventSpanBuffer : true,
            enableEventAnimations : false,
            height                : 360,
            cls                   : 'b-scheduler1',
            startDate             : '2011-01-03',
            endDate               : '2011-01-13',
            features              : {
                eventDrag : {
                    constrainDragToTimeline : false
                }
            },
            eventsData : [
                {
                    id                   : 1,
                    startDate            : '2011-01-04',
                    endDate              : '2011-01-05'
                },
                {
                    id        : 2,
                    startDate : '2011-01-06',
                    endDate   : '2011-01-07'
                }
            ],
            assignmentsData : [
                {
                    id       : 1,
                    event    : 1,
                    resource : 2
                },
                {
                    id       : 2,
                    event    : 2,
                    resource : 2
                }
            ],
            dependenciesData : [],
            calendarsData    : []
        });

        const otherScheduler = await t.getSchedulerProAsync({
            enableEventAnimations : false,
            height                : 360,
            cls                   : 'b-scheduler2',
            startDate             : '2011-01-03',
            endDate               : '2011-01-13',
            features              : {
                eventDrag : {
                    constrainDragToTimeline : false
                }
            },
            eventsData : [
                {
                    id                   : 3,
                    startDate            : '2011-01-04',
                    endDate              : '2011-01-05'
                },
                {
                    id        : 4,
                    startDate : '2011-01-06',
                    endDate   : '2011-01-07'
                }
            ],
            assignmentsData : [
                {
                    id       : 1,
                    event    : 3,
                    resource : 2
                },
                {
                    id       : 2,
                    event    : 4,
                    resource : 2
                }
            ],
            dependenciesData : [],
            calendarsData    : []
        });
    });
```

**Comment by isglass** [comment] 2022-05-09 11:04
Duplicate of #4490 (which was fixed)

**Closed by isglass** 2022-05-09 11:04 UTC
Labels: bug, duplicate
