### ISSUE TITLE
Day/night shift preset looks bad after zoom level change

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#613] opened 2020-04-29 12:33 UTC
Change zoom level or preset, when switching back to day/night shift preset every shift becomes a day shift. also starts at 4 am.
![image](https://user-images.githubusercontent.com/45400762/80596184-a20b4e00-8a2e-11ea-8b40-0d7d8e001b33.png)

**Comment by isglass** [comment] 2024-05-08 14:10
Dupe of #1616

**Closed by isglass** 2024-05-08 14:10 UTC
Labels: bug
