### ISSUE TITLE
Unable to drag and drop rows in Salesforce LWC

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3703] opened 2021-11-10 13:03 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=19367&p=95757#p95757)

[One more post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=20339&p=101028#p101028)

![スクリーンショット 2021-11-07 8.58.50.png](https://www.bryntum.com/forum/download/file.php?id=15341)

I can drag the task, but I can't drop it and it returns to its original location.
Where can I control it here?
![スクリーンショット 2021-11-07 8.58.50.png](https://www.bryntum.com/forum/download/file.php?id=15341)

**Comment by bmblb** [comment] 2022-05-18 06:48
This is a duplicate of resolved issue #4545 , closing

**Closed by bmblb** 2022-05-18 06:48 UTC
Labels: bug, premium, forum, salesforce, OEM

**Comment by freddyLang** [comment] 2022-11-24 23:13
hi,

what is the solution ?

BR

**Comment by bmblb** [comment] 2022-11-25 11:35
@freddyLang do you still see this problem? If you're using older version of the product, I recommend upgrading to latest.

**Comment by freddyLang** [comment] 2022-11-25 11:53
I upgraded the latest version

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
