### ISSUE TITLE
AgendaView range 1 day should not show multiple days

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8854] opened 2024-03-21 14:16 UTC
https://forum.bryntum.com/viewtopic.php?t=28309

When the mode is `day inside agenda view`, there should be only one day shown in the view. This happens by default. But if we add a event with `repeat daily` and the event expands over more then one day, two day are being shown in the view. The issue is when the range size of the `AgendaView is 1 d`, the day into which an event overflows is shown. It should not propagate beyond the end of the view's range.
See the first part of the clip is what user expects (done with bit of tweaking) and second view - last part of video is, what is happening now:

https://github.com/bryntum/support/assets/52177956/6f7ab944-b016-46bf-812d-39bf2bdf76c0

**Comment by ExtAnimal** [comment] 2024-03-30 13:16
Dupe of https://github.com/bryntum/support/issues/8787 which is fixed and from the same user.

**Closed by ExtAnimal** 2024-03-30 13:16 UTC
Labels: bug, forum, large-account, OEM
