### ISSUE TITLE
Setting Array as model field defaultValue leads to it being shared across instances

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3875] opened 2021-12-09 09:32 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=56&t=19728&p=97726#p97726)

TaskBoard version: 4.3.3
Browser version: Google Chrome 91.0.4472.114

Step to reproduce:
Edit a task's todolist value
Create a new task
Edit its todolist value

Expected behavior:

The todolist value should not be replicated on the new created tasks

Scenario:
![bryntum_todolist_linkedTasks.gif](https://www.bryntum.com/forum/download/file.php?id=15760)

**Comment by isglass** [comment] 2022-01-07 10:31
Duplicate of #3849

**Closed by isglass** 2022-01-07 10:31 UTC
Labels: bug, duplicate, resolved, forum
