### ISSUE TITLE
`scheduleContextFeature` config is missing on Scheduler wrappers

### ISSUE THREAD

**Issue by bmblb** [bryntum/support#3135] opened 2021-07-05 13:49 UTC
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=18020&p=89217#p89217
I downloaded 4.2.0 package from NPM and checked wrapper declaration. Indeed there is no `schedulerContextFeature` option there for some reason.
1. Need to check why this feature wasn't added and see if other features are affected
2. Doc states feature is disabled by default, but in code feature is enabled https://bryntum.com/docs/scheduler/#Scheduler/feature/ScheduleContext
Need to bring code and doc to agreement

**Comment by SergeyMaltsev** [comment] 2021-07-05 13:53
The problem is that `scheduleContext` is not marked as `feature` in docs.

**Comment by bmblb** [comment] 2021-07-05 13:56
Can we change feature detection logic to not rely on the doc tag? E.g. maybe process all documented classes with `/features/` in path? That appears more robust at first glance

**Comment by SergeyMaltsev** [comment] 2021-07-05 14:06
It was with this approach recently but actually not all classes under `features` represent real features, some are abstract some util classes or mixins.

**Closed** 2021-07-07 03:57 UTC
Labels: bug, forum, resolved
