### ISSUE TITLE
Error on Undo delete event action

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1468] opened 2020-09-03 10:46 UTC
1. Open "Undo/Redo demo" example
2. Create a new event
3. Delete new created event
4. Click Undo
Error in console appeared: "Uncaught Error: Duplicate assignment Event: _generatedClassDefEx1 to resource: 4"

**Comment by matsbryntse** [comment] 2020-09-04 08:38
Dupe of https://github.com/bryntum/support/issues/1227

**Closed by matsbryntse** 2020-09-04 08:38 UTC
Labels: bug, bugbash, high-priority
