### ISSUE TITLE
Duration Issue using https://bryntum.com/products/gantt/examples/timeranges/

### ISSUE THREAD

**Issue by MRC38** [bryntum/support#6479] opened 2023-03-28 15:59 UTC
I am using your demo site to understand a duration issue I have ,and the demo site is also given me incorrect results.

I set a task to the business calendar, which has working time of 08:00 to 12:00 and 13:00 to 17:00.  I set the task duration to 1 day and the task extends to span 3 days!  I then set the task to 2 days and the duration then extends to 6 days.  Please view the video attached.

https://user-images.githubusercontent.com/34025208/228296314-69a7faa5-80b8-40ac-a667-8e4d96c45875.mp4

**Comment by MRC38** [comment] 2023-03-28 19:18
It seems like there is a problem with any calendar that is not the Default calendar.  You can see on the example below, where i have assigned the Business Calendar to the 'Run Tests' task.  The hoursPerDay on the Business Calendar is 8, not 24 in this instance.  The dates represent a 9 days duration when the duration states 3 days.

![image](https://user-images.githubusercontent.com/34025208/228343281-6aed89cc-44ab-4120-a956-a33a0a45ebdd.png)

**Comment by arcady-zherdev** [comment] 2023-03-29 03:15
[hoursPerDay](https://www.bryntum.com/products/gantt/docs/api/Gantt/model/ProjectModel#field-hoursPerDay) is not a calendar field. It is **in Ext Gantt** only but in the new Gantt the config is moved to the project level.
Here is for example a part of advanced demo dataset:
```json
{
    "success"      : true,
    "project"      : {
        "calendar"     : "general",
        "startDate"    : "2019-01-14",
        "hoursPerDay"  : 24,
        "daysPerWeek"  : 5,
        "daysPerMonth" : 20
    },
    "calendars"    : {
        "rows" : [
...
```
but effectively the proerty anyway was always taken from the project calendar only. So it was decided that it makes more sense

**Comment by arcady-zherdev** [comment] 2023-03-29 16:02
I'm closing the issue since it's caused by a misconfiguration of the data.

**Closed by arcady-zherdev** 2023-03-29 16:02 UTC
