### ISSUE TITLE
[VUE 3] Drag event from grid to scheduler not working

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#9908] opened 2024-08-28 15:00 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=30235&p=153445#p153445)

Dragging events from grid to scheduler doesn't work like normal events

To reproduce download the zip file bellow and follow the steps in the video

https://github.com/user-attachments/assets/65b07944-fc81-4443-b2aa-c64397bedf04

[dispotool-vue-poc_2.zip](https://github.com/user-attachments/files/16785214/dispotool-vue-poc_2.zip)

**Comment by JockeLindberg** [comment] 2024-08-29 07:56
This is caused by using a Scheduler reference included in the `data()` function in Vue, which makes it reactive, which Vue handles by converting to proxys. Closing issue as this is not a fault on our end.

**Closed by JockeLindberg** 2024-08-29 07:56 UTC
Labels: bug, high-priority, in progress, forum
