### ISSUE TITLE
Toolbar items lose their value when moved into toolbar overflow menu

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8813] opened 2024-03-14 15:23 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=28369&p=142582#p142582)

Steps to repro:
1. https://bryntum.com/products/scheduler/examples/dependencies/
2. Change value in terminal settings
3. Resize window in such a way that terminal settings goes to overflow button
4. See the values are different
5. See this clip: https://bryntum.com/products/schedulerpro/examples-scheduler/dependencies/

Hi,

I’m facing an issue with the toolbar items, since it seems that they forget their current value when the window is shrinking, and they are automatically placed in the overflow button.

You can see that behavior in the Scheduler Pro Dependencies demo for example. If you change Terminal Settings -> Terminal Size from 12px to 16px and then make the window smaller so that Terminal Settings ends up in the Overflow Button and then select it again, you will see that it’s value is 12px and not 16px as it should be.

Can you please have a look on this one?

Thanks in advance!
Spiros

**Comment by matsbryntse** [comment] 2024-03-15 08:58
Related? https://github.com/bryntum/support/issues/8523

**Comment by dongryphon** [comment] 2024-03-23 16:37
Probably a duplicate of
- https://github.com/bryntum/support/issues/4933

**Closed** 2024-04-26 10:05 UTC
Labels: bug, resolved, high-priority, forum
