### ISSUE TITLE
UndoRedo doesn't work with flat data structure

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7895] opened 2023-11-19 15:02 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=26978&p=134691#p134691)

Reproducible here https://bryntum.com/products/gantt/examples/undoredo/
By adding this code to projectModel
```javascript
        taskStore: {
            transformFlatData: true,
            autoTree: true,
            data: [
                    {
                        "id": "8dbee327-51bf-42df-ba03-0211824da37a",
                        "name": "a",
                        "parentId": "aedd16c9-7ae4-400c-aa9a-c075404684af",
                        "percentDone": 0,
                        "projectId": "2b127c53-8481-45aa-9e07-4cbebb705d9b",
                        "startDate": "2023-08-31T08:00:00",
                        "endDate": "2023-08-31T15:30:00",
                        "duration": 1,
                        "durationUnit": "day",
                        "calendar": "2b389035-8083-499b-a46b-561e1269f817",
                        "constraintType": "",
                        "constraintDate": null,
                        "expanded": true,
                        "schedulingMode": "FixedDuration",
                        "projectGroupColor": null,
                        "customColor": 16777215,
                        "effortDriven": true,
                        "manuallyScheduled": false,
                        "parentIndex": 0,
                        "isPublication": false,
                        "isProjectGrouping": false,
                        "readOnly": false
                    },
                    {
                        "id": "aedd16c9-7ae4-400c-aa9a-c075404684af",
                        "name": "New task",
                        "parentId": null,
                        "percentDone": 0,
                        "projectId": "2b127c53-8481-45aa-9e07-4cbebb705d9b",
                        "startDate": "2023-08-31T08:00:00",
                        "endDate": "2023-08-31T15:30:00",
                        "duration": 1,
                        "durationUnit": "day",
                        "calendar": "2b389035-8083-499b-a46b-561e1269f817",
                        "constraintType": "",
                        "constraintDate": null,
                        "expanded": true,
                        "schedulingMode": "FixedDuration",
                        "projectGroupColor": null,
                        "customColor": -65536,
                        "effortDriven": true,
                        "manuallyScheduled": false,
                        "parentIndex": 0,
                        "isPublication": false,
                        "isProjectGrouping": false,
                        "readOnly": false
                    },
                    {
                        "id": "76a09cd7-9cdb-4490-80c6-fd428ce8ad59",
                        "name": "b",
                        "parentId": null,
                        "percentDone": 0,
                        "projectId": "2b127c53-8481-45aa-9e07-4cbebb705d9b",
                        "startDate": "2023-08-31T08:00:00",
                        "endDate": "2023-08-31T15:30:00",
                        "duration": 1,
                        "durationUnit": "day",
                        "calendar": "2b389035-8083-499b-a46b-561e1269f817",
                        "constraintType": "",
                        "constraintDate": null,
                        "expanded": true,
                        "schedulingMode": "FixedDuration",
                        "projectGroupColor": null,
                        "customColor": 16777215,
                        "effortDriven": true,
                        "manuallyScheduled": false,
                        "parentIndex": 1,
                        "isPublication": false,
                        "isProjectGrouping": false,
                        "readOnly": false
                    }
                ]
        }
```
Video

https://github.com/bryntum/support/assets/75997756/a4cf258f-b142-4913-8c95-ed337e381a76

**Comment by canonic-epicure** [comment] 2024-01-03 07:53
The undo/redo buttons and actions grid remains empty simply because the `stm` instance is not enabled. Once enabled manually (either via `enable()` method call or as `disabled = false` `stm` config) everything works.

`stm` instance is enabled automatically by the UndoRedo widget, which does that in the listener for the project's `load` event. If project does not use `autoLoad` facility and instead loads the data manually, one need to enable `stm` manually as well.

Closing this one as "works as intended".

**Closed by canonic-epicure** 2024-01-03 07:53 UTC
Labels: bug, high-priority, in progress, premium, forum, large-account
