### ISSUE TITLE
Returning false from beforeUpdate does not revert event D&D

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#3765] opened 2021-11-18 08:20 UTC
![beforeupdate](https://user-images.githubusercontent.com/204844/142378352-f328111b-2df1-4b9f-b166-a2ef3c42dd44.gif)

Note: Non-Pro scheduler works as expeted.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?p=96295#p96295)

Hi there,

I am in the middle of adapting SchedulerPro to our graphql backend. Fetching data from the backend was implemented by simply setting eventStore.data with the result of the last useQuery-hook of ApolloGraphQL. We poll data from the backend and we have enabled syncDataOnLoad on the eventStore. We have a simple ProjectModel with some additional fields but nothing spectacular. We use the react component and use the refCallback to get access to the scheduler.

Now we try to implement error handling, specifically when a graphql request has failed that was supposed to update startDate, endDate, resourceId to the new values the user has supplied after a drag operation in the scheduler. Until now we used the update event on eventStore to communicate changes to the graphql backend. But since this can fail, the attempted change has to be reverted. We attempted the following things with our limited knowledge about the scheduler to no success:
rerendering the component (the apollo hook still returns the unmodified set of events since the update mutation failed)
changing the values of startDate and endDate back from within the update callback like this:

```
updateEvent.record.startDate = oldStartDate;
updateEvent.record.endDate = oldEndDate;
```
This causes an infinite loop because this is recognized as an update itself and triggers another update event
using eventStore.suspendEvents(false) / resumeEvents() to remedy that this triggers an update event. Unfortunately the update event is still triggered.
changing the original data like this:

```
updateEvent.record.data.startDate = oldStartDate;
updateEvent.record.data.endDate = oldEndDate;
```
This does nothing, the scheduler still paints the changed values that were rejected by the update mutation
using crudManager beforeCommit event and returning false. Again the event is still painted at the new position that was rejected by the update mutation

What am I doing wrong? It seems that every approach that seems to be suggested by some part of the documentation fails and it is very frustrating. In my opinion the documentation fails to give a clear and detailed explanation of the inner workings of your components. Also I couldn't find any example that covers my use case where I could have get some inspiration. Creating standalone examples of this will be hard and also very time consuming and I am not looking forward to that.

**Comment by magicflute87** [comment] 2022-07-13 13:13
Looking for a solution for a similar use case as well.

**Comment by matsbryntse** [comment] 2022-11-29 08:58
Closing as WontFix, validation layer planned for 7.0

**Comment by matsbryntse** [comment] 2022-11-29 08:59
You can use https://bryntum.com/products/schedulerpro/docs/api/Scheduler/feature/EventDrag#event-beforeEventDropFinalize to validate your drag drop asynchronously

**Comment by keithhackbarth** [comment] 2023-02-17 19:58
Also, experience this as a defect. The expectation from the documentation is that the returning false from beforeUpdate would repaint here. 

It is unclear how a validation layer would resolve this as the issue is with the store layer.

**Comment by matsbryntse** [comment] 2023-02-18 09:18
We'll take another look to see if we can make this work according to expectations.

**Closed** 2023-04-04 11:58 UTC
Labels: bug, resolved, forum, OEM
