### ISSUE TITLE
[SALESFORCE] Gantt and TaskBoard issues on Firefox with Debug Mode disabled

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#8234] opened 2024-01-11 18:30 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=27545&p=137904#p137904)

Hi there,

We've encountered some issues in our implementations of the Gantt and TaskBoard components that only occur using Firefox when Debug Mode is disabled on the org.

In Gantt we're calling loadCrudManagerData but data is not loaded in the above scenario, whereas in TaskBoard we're calling loadDataAsync on each of the stores independently (data does get loaded but we're awaiting the promises before releasing a custom load mask, which never get resolved).

We haven't managed to reproduce these specific issues in the provided Salesforce demo org but are seeing a number of other defects under the same org setup that may be related. If the demo components are loading data inline that could be the reason that they are loading data successfully whereas ours don't.

Gantt examples:
Critical paths feature does not highlight critical path when toggled using toolbar button.
New tasks do not have a default start date.
Inline edit doesn't trigger on cell double click.
Edit modal doesn't trigger on tasks.
Undo / redo buttons are not working.

TaskBoard example:
Component freezes when dragging / dropping a task to another column or swimlane.

These features all work as expected with Debug Mode enabled, and on other browsers with Debug Mode disabled. See attached a video showing the different behaviour, initially with Debug Mode disabled then with Debug Mode enabled. This might be related to the issues we're seeing with data loads in our own implementations.

https://github.com/bryntum/support/assets/7203098/6a75184a-b801-4846-b2e2-a3cb2cb8eaba

https://github.com/bryntum/support/assets/7203098/8e135bec-c6f8-4f49-b9b2-1fba575b221e

Thanks,
Callum

**Comment by amurashincertinia** [comment] 2024-02-20 21:22
I'd like to share a quick update on this issue.

There is likely a bug in Lightning Web Security. When it is enabled, and only if LWC Debugging is switched off, the following line of code stops working in Firefox if the script was loaded from a Static Resource:

```js
await Promise.resolve();
```

I used this simple reproduction to narrow this down and eliminate any possible side effects caused by your code:

```js
(async () => {
    console.log('PING');
    await Promise.resolve();
    console.log('PONG');
})();
```

When loaded by a Lightning Web Component from Static Resources, it will output two messages in the Developer Tools console in any browser but Firefox under the conditions described above. Switching LWS off or enabling LWC Debugging also "fixes" it, so it is a quite unique situation, unfortunately.

I have reported this to Salesforce. There are no workarounds available AFAIK.

**Comment by matsbryntse** [comment] 2024-07-28 07:48
@amurashincertinia Thanks for the update, closing this until we hear if Salesforce intends to fix the bug.

**Closed by matsbryntse** 2024-07-28 07:48 UTC
Labels: bug, wontfix, high-priority, premium, forum, salesforce, large-account, OEM

**Comment by amurashincertinia** [comment] 2024-07-29 14:16
Hi Mats,

[According to Salesforce](https://developer.salesforce.com/docs/platform/lwc/guide/security-lwsec-async.html), this is actually a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1663090).

Our workaround is to use Babel with `@babel/plugin-transform-async-to-generator` and `@babel/plugin-transform-async-generator-functions` plugins to build the bundle for LWC.
