### ISSUE TITLE
Should include assignments when copying/pasting tasks

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8529] opened 2024-02-12 07:44 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=27943&p=140253#p140253)

Is it possible to copy/paste the assignments on a task. Right now it copies all the rest of the data. If not can you please add to your backlog.

**Comment by JockeLindberg** [comment] 2024-04-25 10:17
Duplicate of https://github.com/bryntum/support/issues/3655

**Closed by JockeLindberg** 2024-04-25 10:17 UTC
Labels: feature request, forum
