### ISSUE TITLE
Agenda view is not printable

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#4016] opened 2022-01-13 17:26 UTC
Shows just whitespace 
https://www.bryntum.com/forum/viewtopic.php?f=54&t=20005&p=99189#p99189

**Comment by ExtAnimal** [comment] 2022-08-12 09:01
This is a duplicate of this: https://github.com/bryntum/support/issues/3884

We've tried a couple of times to fix this. The correct fix is in the Grid export class. Grid export to PDF needs to be made more capable to export multiple pages, variable height rows, and break pages between  rows.

**Closed** 2023-04-03 06:49 UTC
Labels: bug
