### ISSUE TITLE
Replacing calendars with same id causes an error

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#5718] opened 2022-12-06 03:54 UTC
[inline-data.zip](https://github.com/bryntum/support/files/10162093/inline-data.zip)

Also data in timeline didn't reflect.
disabling `syncDataOnLoad` for CalendarStore didn't help, but data on timeline starts updating.

[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=23083&p=114623#p114623)

Hi guys!
I'm obtaining tasks and calendars for the tasks via api and setting it on the gantt via setTasks[]  and setCalendars[]. Evetything works fine during the first load.
However, if I'm loading additional tasks via api and resetting both tasks and calendar, I'm receiving the following error.
![Capture2.PNG](https://forum.bryntum.com/download/file.php?id=19711)
Does it mean that the calendars should be like a static config that could not be changed once the gantt is loaded?
![Capture2.PNG](https://forum.bryntum.com/download/file.php?id=19711)

```
gantt.module.js:179830 Uncaught (in promise) Error: Unknown identifier ClassDefEx-32.$.effectiveCalendar
    at throwUnknownIdentifier (gantt.module.js:179830:1)
    at EngineTra

nsaction.onReadIdentifier (gantt.module.js:180662:1)
    at EngineTransaction.calculateTransitionsStackGen (gantt.module.js:180793:1)
    at calculateTransitionsStackGen.next (<anonymous>)
    at EngineTransaction.calculateTransitions (gantt.module.js:180701:1)
    at calculateTransitions.next (<anonymous>)
    at runGeneratorAsyncWithEffect (gantt.module.js:179267:1)
    at gantt.module.js:180569:1
```

**Comment by canonic-epicure** [comment] 2022-12-09 08:56
The timeline is actually updated, its just the tasks are scheduled far forward in the future (because of dependencies), thats why they are not visible.

**Comment by canonic-epicure** [comment] 2022-12-09 09:18
Or, perhaps the ticket is talking about the #5602 (duplicate of #5394). I'll be focusing on the exception thrown in this ticket.

**Comment by canonic-epicure** [comment] 2022-12-09 09:57
The original exception is not reproducible. The "secondary" exception seems to be caused by the id duplication in the data, which should be fixed of course, but not critical compared to the original I guess. Requested new steps to reproduce the original exception.

**Closed** 2022-12-28 10:37 UTC
Labels: bug, resolved, high-priority, forum, OEM
