### ISSUE TITLE
Group summary in collapsed state.

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1758] opened 2020-10-28 08:40 UTC
User wants to see summary info for collapsed group. Add a flag to manage summary visibility for collapsed groups in `groupSummary` feature.

Should work for subGrids too.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15700&p=78534)

**Comment by isglass** [comment] 2020-11-02 12:07
Duplicate of #1355

**Closed** 2020-11-02 12:08 UTC
Labels: duplicate, feature request, forum
