### ISSUE TITLE
Export demo problems

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1554] opened 2020-09-22 12:44 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=15350&p=77164#p77164)

Hello,

While trying to verify the default scheduler behavior for exporting, I ran into 2 problems:

On Edge (old version, not Chromium-based, 44.18362.449.0 to be precise), the export fails, with the following error in console:

```
HTTP405: BAD METHOD - The HTTP verb used is not supported.
(Fetch)OPTIONS - http://localhost:8080/
Unhandled promise rejection TypeError: Failed to fetch
```
When trying to export with Visible schedule and Visible rows (the other options don't matter) while being at the bottom of the schedule (row 100 is in view), it gets stuck on generating pages (I had it open for 15+ mins at the time of writing and no progress). This happens on Chrome, but it's probably independent of browser.

**Comment by r-cristian-v** [comment] 2020-09-23 07:01
As further info for this
 - for the first point, we changed the export flow in our application so that it doesn't make the request anymore and instead we handle everything client-side with jsPDF and html2canvas, but we didn't touch the html generation at all. Because of this we don't get the same problem as the one I reported, however, we noticed that if you choose the option to print all rows in Edge while not being at the top of the schedule, some rows will be not be exported, and some will be duplicated. Might be worth checking this after fixing the fetch problem.
 - for the second point, in our application, for this scenario (bottom of the schedule, visible rows), if we have a structure along the lines of 
* row1
* row2
* row3
* row4
* row5
with rows 3-5 in view, it will instead export rows 2-4, completely ignoring the bottom one.

**Comment by r-cristian-v** [comment] 2020-10-16 08:37
Any updates for this?

**Comment by matsbryntse** [comment] 2021-04-08 15:37
Are both these issues only related to old Edge? Please keep in mind we will drop support for legacy Edge May 1st.

**Comment by bmblb** [comment] 2021-04-08 19:30
@r-cristian-v I see you're using client side pdf generation with jsPDF and html2canvas, how well does it work for you? Any artifacts in the exported page? Like box size difference or misplaced dependency lines?

**Comment by r-cristian-v** [comment] 2021-04-09 10:19
@matsbryntse Only one of the them was related to old Edge. 
I tried the export demo again in case you updated it to use the new 4.1 version. Unfortunately the new Edge was pushed company wide and getting the old one to run in parallel is a bit of pain so that will have to wait a bit, but I did check it in Chrome, and I still see 2 issues:

1. if I'm at the bottom of the schedule and I print visible schedule + visible rows bryntum seems to remain stuck on generating the pages (it might just take longer, but as a user you can't really sit around doing nothing for a couple of minutes)
2. if I choose to print only visible rows (while at the top of the schedule to make sure it works), with rows 1-8 in view, it's going to actually export rows 1-16, so what exactly does 'visible' mean? 

@bmblb it's good enough, but it doesn't beat the implementation you guys have right now. In usual cases it's the same, but doing something out of the ordinary like printing the whole schedule on a single page, you can't really zoom in on the pdf afterwards since everything is pixelated because of how we're generating the file. There's also the problem that the memory usage can skyrocket during the process depending on the options you pick, which can cause IE11 to crash if it goes over a certain threshold (I can't remember the actual number right now)

**Comment by bmblb** [comment] 2021-04-09 10:42
@r-cristian-v thanks for the update. Not sure what is the problem with zoom exactly, it looks like `transform: scale()` should've done the trick.
Speaking of issues, both of them should be fixed in the related PR

**Comment by r-cristian-v** [comment] 2021-04-09 10:59
@bmblb Great news! So the fix should be part of 4.1.1, right?

**Comment by bmblb** [comment] 2021-04-09 11:03
@r-cristian-v it appears so, yes. I'd appreciate if you'd try nightly build, which you can get in the customer zone the day after related PR is merged, to see if issue is no longer reproducible on your end.

**Comment by bmblb** [comment] 2021-04-12 08:07
@r-cristian-v have you got a chance to try nightly build to see if issue is fixed for you?

**Comment by r-cristian-v** [comment] 2021-04-12 08:42
@bmblb It's on today's TODO list. I see 2 branches, next and release, which one should I try?

**Comment by bmblb** [comment] 2021-04-12 08:45
@r-cristian-v release. next is a branch for the next major release

**Comment by r-cristian-v** [comment] 2021-04-13 10:53
I can't the reproduce the issues I reported a couple of days ago on the april 12 build.
I noticed a minor problem, if I export the bottom of the schedule it won't properly scroll back to it (ie. it goes to row 98 in the example instead of 100), but it's not that big of an issue.
Still trying to get Edge legacy running, I'll try and have that tested also by the end of this week.

**Comment by r-cristian-v** [comment] 2021-04-14 14:23
Everything's fine for Edge legacy too. I also went back and re-tested our application for the initial issue cause I had a hunch the problem we initially had found was related to the Edge version used for testing, which turned out to be true.

Is https://github.com/bryntum/support/issues/318 also ready to be tested?

**Comment by bmblb** [comment] 2021-04-14 14:25
@r-cristian-v yes, nightly build should contain fix for the mentioned problem. There are still issues with DST, but this particular case is handled

**Closed** 2021-04-23 06:54 UTC
Labels: bug, forum, high-priority, pdf export, resolved
