### ISSUE TITLE
Scheduler's filter function breaks when used together with grouping function (screenrec)

### ISSUE THREAD

**Issue by Valentino30** [bryntum/support#371] opened 2020-02-28 15:07 UTC
`Bryntun Scheduler v. 3.0.4`

**How to reproduce (see attached screen recording):**

1. Add `filterBar: true` to [Grouping Demo](https://www.bryntum.com/examples/scheduler/grouping/)
2. Collapse `Consultants` group
3. Filter by `Name` (i.e. Brett)

**Buggy Outcome (see attached screen recording):**

- Groups that do not contain the filter keyword disappear 
- Resources shown do not match the filter keyword

**Expected outcome:**

- Keep showing all `Groups`
- Expand only the `Groups` that contain `Consultants` who's name matches the filter keyword
- Within the expanded `Groups`, show only the `Consultants` who's name matches the filter keyword

[screencast-www.bryntum.com-2020.02.zip](https://github.com/bryntum/support/files/4267623/screencast-www.bryntum.com-2020.02.zip)

**Comment by matsbryntse** [comment] 2021-07-18 21:31
Duplicate of #1596

**Closed by matsbryntse** 2021-07-18 21:31 UTC
Labels: bug
