### ISSUE TITLE
Not possible to use collapsible panels in ExtJS Modern demo

### ISSUE THREAD

**Issue by isglass** [bryntum/support#1] opened 2019-11-07 10:47 UTC
Reported here: https://www.bryntum.com/forum/viewtopic.php?f=44&t=12600&p=66197#p66197

See https://app.assembla.com/spaces/bryntum/tickets/9454/details

 - [ ] Update demo
 - [ ] Cover with test

**Comment by dongryphon** [comment] 2020-01-04 23:40
Should be fixed by https://github.com/bryntum/bryntum-suite/pull/375

**Comment by dongryphon** [comment] 2020-01-04 23:41
Likely a duplicate of https://github.com/bryntum/support/issues/91

**Comment by dongryphon** [comment] 2020-01-29 12:32
This override fixes the problem (from https://github.com/bryntum/bryntum-suite/pull/529):
```javascript
Ext.define('Bryntum.Compat', {
    override : 'Ext.dom.Element'
},
function(Element) {
    var eventMap = Element.prototype.eventMap;

    if (eventMap) {
        // Since 5.1.0, Ext JS has preferred webkit* vendor prefix for these. In the
        // past both webkitTransitionEnd and the standard transitionend event would be
        // fired, but in Chrome 79 (though the change was likely earlier), this is no
        // longer true. Since Bryntum Core requires the standard event, it is fair to
        // simply remove these from the mapping used by Ext JS (it will then use the
        // standard events as well):
        delete eventMap.transitionend;
        delete eventMap.animationstart;
        delete eventMap.animationend;
    }
});
```

**Closed by dongryphon** 2020-01-29 12:32 UTC
Labels: bug, ready for review
