### ISSUE TITLE
Race condition bug when clicked undo/redo fast

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#3698] opened 2021-11-10 08:19 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=19407&p=95948#p95948)

Reproduced on https://bryntum.com/examples/gantt/advanced/
Make few changes to have 6-10 steps undo. As example, create 5 events and make dependencies one by one.
Click undo/redo fast, it will throw an error in console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'get')
    at _0x305c19.equality (gantt.module.js?454302:13)
    at EngineTransaction.onQuarkCalculationCompleted (gantt.module.js?454302:13)
    at EngineTransaction.calculateTransitionsStackGen (gantt.module.js?454302:13)
    at Generator.next (<anonymous>)
    at EngineTransaction.calculateTransitions (gantt.module.js?454302:13)
    at Generator.next (<anonymous>)
    at runGeneratorAsyncWithEffect (gantt.module.js?454302:13)
    at gantt.module.js?454302:13
```

**Comment by isglass** [comment] 2022-04-22 13:07
Could not reproduce it, asked @chuckn0rris to try. Might have been fixed by other changes

**Comment by isglass** [comment] 2022-05-03 08:42
To reproduce:
1. Open advanced demo
2. Click `+ Create` twice
3. Drag create a dependency from the first new tasks end to second ones start
4. Undo twice
5. Redo

**Comment by canonic-epicure** [comment] 2022-11-30 06:58
Does not seem to be reproducible anymore in the online examples, probably has been already fixed.

**Comment by canonic-epicure** [comment] 2022-11-30 07:01
Please provide new steps to reproduce.

**Comment by matsbryntse** [comment] 2022-11-30 07:36
Closed until new repro sequence is available

**Closed by matsbryntse** 2022-11-30 07:36 UTC
Labels: bug, Info requested, high-priority, in progress, premium, forum, OEM
