### ISSUE TITLE
Custom keyMap for navigation doesn't work in Scheduler

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#7005] opened 2023-06-15 09:30 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?t=25323&e=1&view=unread#unread)

1. Docs needs to be fixed. It inherited from Grid, but in Scheduler code snippets from docs doesn't work  https://bryntum.com/products/scheduler/docs/guide/Scheduler/customization/keymap
2. Try this 
```
keyMap : {
  w : () => {

    scheduler.navigateUp();
},
s : () => {

    scheduler.navigateDown();
},
a : () => {

    scheduler.navigateLeft();
},
d : () => {

    scheduler.navigateRight();
},

},
```
navigation  doesn't work as expected. It should be working same as using arrows, but it doesn't
3. Seems like using string as keyMap function name (`a: 'navigateUp'`) will use Grid's scope and if the method doesn't exist in Grid, it won't be working. 
4. It required to add code snippet with using function notation as a value for keyMap key. Users don't know it's possible to use functions.

**Comment by JockeLindberg** [comment] 2023-06-16 08:00
Closing as its a duplicate of #4723 and #6918

**Closed by JockeLindberg** 2023-06-16 08:00 UTC
Labels: bug, forum, OEM
