### ISSUE TITLE
Problems with rendering React component in column renderer and as cell editor

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4308] opened 2022-03-04 09:08 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=20467&p=101551#p101551)

https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/

Try to dblclick on React "Edit" button - see an error in console.
```
rootcause-full.js:10 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at ca (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:407879)
    at fl (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:421138)
    at t.unstable_runWithPriority (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:441891)
    at Wi (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:366022)
    at hl (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:418996)
    at Ja (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:415127)
    at https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:366313
    at t.unstable_runWithPriority (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:441891)
    at Wi (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:366022)
    at Gi (https://bryntum.com/examples/gantt/frameworks/react/javascript/basic/build/static/js/2.a3594421.chunk.js:74:366258)
e.<computed> @ rootcause-full.js:10
ea @ 2.a3594421.chunk.js:74
n.callback @ 2.a3594421.chunk.js:74
ho @ 2.a3594421.chunk.js:74
oa @ 2.a3594421.chunk.js:74
fl @ 2.a3594421.chunk.js:74
t.unstable_runWithPriority @ 2.a3594421.chunk.js:74
Wi @ 2.a3594421.chunk.js:74
hl @ 2.a3594421.chunk.js:74
Ja @ 2.a3594421.chunk.js:74
(anonymous) @ 2.a3594421.chunk.js:74
t.unstable_runWithPriority @ 2.a3594421.chunk.js:74
Wi @ 2.a3594421.chunk.js:74
Gi @ 2.a3594421.chunk.js:74
Ui @ 2.a3594421.chunk.js:74
Ya @ 2.a3594421.chunk.js:74
enqueueSetState @ 2.a3594421.chunk.js:74
C.setState @ 2.a3594421.chunk.js:74
(anonymous) @ 2.a3594421.chunk.js:74
requestAnimationFrame (async)
(anonymous) @ 2.a3594421.chunk.js:74
c @ 2.a3594421.chunk.js:74
renderCell @ 2.a3594421.chunk.js:35
render @ 2.a3594421.chunk.js:35
renderFromRow @ 2.a3594421.chunk.js:45
refresh @ 2.a3594421.chunk.js:45
refreshRows @ 2.a3594421.chunk.js:45
refreshRows @ 2.a3594421.chunk.js:60
refresh @ 2.a3594421.chunk.js:60
(anonymous) @ 2.a3594421.chunk.js:60
runWithTransition @ 2.a3594421.chunk.js:60
refreshWithTransition @ 2.a3594421.chunk.js:60
internalOnProjectRefresh @ 2.a3594421.chunk.js:74
trigger @ 2.a3594421.chunk.js:2
finalizeCommitAsync @ 2.a3594421.chunk.js:60
doCommitAsync @ 2.a3594421.chunk.js:60
await in doCommitAsync (async)
(anonymous) @ 2.a3594421.chunk.js:60
Promise.then (async)
commitAsync @ 2.a3594421.chunk.js:60
commitAsync @ 2.a3594421.chunk.js:60
commitAsync @ 2.a3594421.chunk.js:60
doCancel @ 2.a3594421.chunk.js:60
..........
```

Try to dblclick on Draggable column that uses React component as an editor. See that React component is not renderered, only text "Yes" will be shown.

Same problem in
https://www.bryntum.com/examples/grid/frameworks/react/javascript/basic/

**Comment by jsakalos** [comment] 2022-03-15 13:25
I cannot reproduce it. Is there anything what I'm not doing?
![react-editor](https://user-images.githubusercontent.com/204844/158387458-2f303e5f-6d58-4e2c-91be-e51fa3fef99c.gif)

**Comment by jsakalos** [comment] 2022-04-04 09:17
2nd part is probably the duplicate of #4291

**Comment by eiglow** [comment] 2022-04-05 00:15
I think the first part is also related to #4291, I have also run into that error when using a custom react component for the cell editor.

**Comment by jsakalos** [comment] 2022-04-06 09:37
@eiglow do you have any runnable showcase of that? As you can see on screencast I cannot reproduce the crash with our basic demo.

**Comment by jsakalos** [comment] 2022-04-06 12:07
I could reproduce the crash by activating the editor (which does not work properly) and then fast scrolling up and down. It may be caused by react component not being rendered properly #4291 so that scrolling buffering does not find an expected element so it crashes.
![react-editor-crash](https://user-images.githubusercontent.com/204844/161970801-8969be74-917e-4460-87b9-02d6b792e560.gif)

This needs to be re-checked after fixing #4291

**Closed** 2022-04-13 12:40 UTC
Labels: bug, regression, example, resolved, ready for review, forum, large-account, OEM
