### ISSUE TITLE
Event height not being updated when fixed row height set to true

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#10125] opened 2024-09-26 14:21 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=51&t=30553&p=155100#p155100)

"Hi,

  I want to have fixed row height , if the events are stacked it should reduce the height of the event to accommodate row height.
![row height-old.PNG](https://forum.bryntum.com/download/file.php?id=30980)
![fixed row height.PNG](https://forum.bryntum.com/download/file.php?id=30979)"

- Go to https://bryntum.com/products/schedulerpro/examples/nested-events/
- Add `fixedRowHeight: true`
- Copy and paste several times any event, to see the behavior in the attached video.

https://github.com/user-attachments/assets/a67a7055-ecd3-449f-9b6c-dd6974511c48

**Comment by isglass** [comment] 2024-10-02 06:07
Will close this issue, it is not a bug. `fixedRowHeight` & stack layout does not make sense to combine. fixedRowHeight is for performance optimization when all rows will use the same row height, while stack means rows should grow when events overlap. They cannot be combined

**Closed by isglass** 2024-10-02 06:07 UTC
Labels: bug, premium, forum, OEM
