### ISSUE TITLE
TabPanel should have Panel's functionality

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#915] opened 2020-06-11 08:09 UTC
Since TabPanel has "Panel" in the name, I assume it has all the features a Panel has. But it's not, since it extends a Container.

Usecase is when you need to add a tbar or bbar to a TabPanel you have to additionally wrap it into a Panel.

Panel is deeply involved into theming. So additional work might be required to check how TabPanel looks in all our themes.

Or simply rename TabPanel to TabContainer

**Comment by isglass** [comment] 2020-12-16 08:32
Closed as duplicate of #1837

**Closed by isglass** 2020-12-16 08:32 UTC
Labels: feature request
