### ISSUE TITLE
Navigate between recurring event on Agenda view

### ISSUE THREAD

**Issue by fabiojpoli** [bryntum/support#1872] opened 2020-11-13 13:32 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=15877&p=79255#p79255)

Currently is not possible navigate for recurring events on agenda view.

Here are @ExtAnimal notes about that:

> Could be build into the populateStore method when the widget creates rows for the dates that events occupy.
> Some configurable quantum by which the populateStore method looks ahead and creates the next few weeks.
> 
> AgendaView will pick up some more configurability with regard to what time range it encompasses soon anyway.
> There are requests for things like a Year agenda or Month agenda which means that it would have a known date range to use to populate its rows.

**Comment by isglass** [comment] 2020-11-16 07:59
Duplicate of #1875

**Closed** 2020-11-16 08:01 UTC
Labels: feature request, forum
