### ISSUE TITLE
Add new events does not work after clicking cancel in Vue event editor demo

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#389] opened 2020-03-05 07:47 UTC
`im going to buy scheduler. could you check a bug on Vue Custom Event Editor demo. 
when i add new event, the modal appear as you know. after save the event, timeline is broken. 
which one is problem do you know? also could you guys fix it? 
 
thank you`

https://bryntum.com/examples/scheduler/vue/javascript/custom-event-editor/dist/index.html

1. double click to create
2. click cancel
3. double click to create -> nothing happens

**Comment by jsakalos** [comment] 2020-03-05 08:39
This is most likely a duplicate of already fixed https://github.com/bryntum/support/issues/380 
Need a clarification from the client to be sure.

**Closed** 2020-03-06 08:58 UTC
Labels: high-priority, question, vue
