### ISSUE TITLE
Implement Recurring Events UI support for Scheduler Pro

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#1556] opened 2020-09-23 08:22 UTC
Recurring events are supported from version 4.0.0 but there is no UI support for it (info from @isglass).

---

[Forum post](https://bryntum.com/forum/viewtopic.php?f=44&t=15358&p=77189#p77189)

Hello - Are recurring events supported with Scheduler Pro?  I am able to get recurring events to work with Scheduler using the 'enableRecurringEvents' config, however, when using SchedulerPro, this config does not work.

Thanks!

**Comment by ExtAnimal** [comment] 2020-09-23 08:43
This should work in 4.0

recurring events are produced by the data layer.

**Comment by ExtAnimal** [comment] 2020-09-23 08:51
In fact there's already an example: `/bryntum-suite/SchedulerPro/examples-scheduler/recurrence/`

**Comment by tmay-sitetracker** [comment] 2020-09-23 16:17
> In fact there's already an example: `/bryntum-suite/SchedulerPro/examples-scheduler/recurrence/`

If I'm looking at the [correct example](https://www.bryntum.com/examples/examples-scheduler/recurrence/) you are referring to, it seems to be using the regular Scheduler, not SchedulerPro.  I am able to get things to work correctly when using Scheduler, but not using SchedulerPro.

If this is not the correct example, could you please point me to the right one?

**Comment by jsakalos** [comment] 2020-09-24 10:00
The above demo is really using Scheduler, not SchedulerPro. We need to implement the UI as stated in the text of the ticket.

**Comment by matsbryntse** [comment] 2021-04-12 08:47
Duplicate of #792

**Closed by matsbryntse** 2021-04-12 08:47 UTC
Labels: bug, forum, high-priority
