### ISSUE TITLE
Error when change month in Calendar

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1539] opened 2020-09-18 12:48 UTC
1. Open "basic" calendar example.
2. Try to change month in datepicker on sidepanel using ">" button.
An error in the console has been appeared.

Reproduced in master.

**Comment by isglass** [comment] 2020-09-18 12:59
Duplicate of https://github.com/bryntum/support/issues/1520

**Closed** 2020-09-18 12:59 UTC
Labels: bug, duplicate
