### ISSUE TITLE
Highlighting child tasks in a new layer

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1290] opened 2020-08-04 08:37 UTC
It should be a feature that supports CSS customization.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=52&t=14829&p=75258)

My Requirement is:
How can I add a task layer background (Light shaded bg) under the parent tasks.  This background is displayed behind the respected child tasks around. 
Means  Parent task -> child tasks -> light background with border for around the child task.
![taskbg.png](https://www.bryntum.com/forum/download/file.php?id=10889)

Thanks
Nagaraju

**Comment by fabiojpoli** [comment] 2020-08-04 10:47
We support this in old Ext version, in action here: https://bryntum.com/examples/gantt-for-extjs/advanced/#en click cog in top right, then Toggle task grouping.

**Comment by fabiojpoli** [comment] 2020-08-04 13:42
After implemented, make a test to be sure the background will expand/collapse with the task.

**Comment by mirceabizdadea** [comment] 2021-06-18 08:03
After implementation, please also test the following scenario:

1. Having a large set of data on the same project
2. Activate the background feature
3. Scroll down

Make sure the background is still visible. We noticed that the tasks are removed from the DOM when you scroll down. ;)

**Comment by matsbryntse** [comment] 2021-07-26 21:17
Duplicate of https://github.com/bryntum/support/issues/209

**Closed by matsbryntse** 2021-07-26 21:17 UTC
Labels: feature request, forum, ready for review
