### ISSUE TITLE
Auto scheduled child not following manually scheduled parent constraints

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8481] opened 2024-02-06 11:13 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?p=139870#p139870)

Hi,

See screenshot below.

![Bryntum-2024-02-06-003.png](https://forum.bryntum.com/download/file.php?id=26704)

We can't make sense of how this task is positioned. It's like the automatic scheduling is not constrained to its parent. This is a bug, right ?

[Bryntum-2024-02-06-003.zip](https://github.com/bryntum/support/files/14258285/Bryntum-2024-02-06-003.zip)

**Comment by FlowIT-JIT** [comment] 2024-02-07 12:36
We are about to release our Gantt implementation after 18 months of development, but this bug is blocking us from moving forward. Will a fix make it to the upcoming patch release ?

**Comment by arcady-zherdev** [comment] 2024-02-12 12:14
@FlowIT-JIT We are investigating the issue at the moment and will let you know of results after it's done. No worries the ticket is already prioritized so should be fixed soon.

**Comment by FlowIT-JIT** [comment] 2024-02-12 12:16
Thanks a lot @arcady-zherdev 😊

**Comment by arcady-zherdev** [comment] 2024-02-13 09:06
@FlowIT-JIT Ok we've found the reason. It's in the code calculating earliest/latest task dates.

The root cause of the issue is a scheduling conflict in the data of course. It's silenced since you use `manuallyScheduled` mode for "Ide" task. And if you make it automatically scheduled it will jump to the same date "Opgave Ide" gets scheduled.

We'll try to change the code to handle that case more gracefully.

**Comment by FlowIT-JIT** [comment] 2024-02-13 11:54
Awesome - thanks for keeping us updated, @arcady-zherdev

**Closed** 2024-02-22 11:55 UTC
Labels: bug, resolved, high-priority, premium, forum, large-account, OEM
