### ISSUE TITLE
Convert string params to enumerators in Typescript

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7893] opened 2023-11-17 20:28 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=26974&p=134670#p134670)

"It is possible to declare an enumerator in the TS definition file for the values 'circular', 'memory' and 'local' instead of using these fixed values in the union params?

This will help me with my source generator I am creating here, that not accept this type of param."

**Comment by isglass** [comment] 2023-11-21 06:46
Duplicate of https://github.com/bryntum/support/issues/3583

**Closed by isglass** 2023-11-21 06:46 UTC
Labels: feature request, forum, OEM
