### ISSUE TITLE
Struggling with bugs, inconsistencies, and anti-patterns

### ISSUE THREAD

**Issue by FlowIT-JIT** [bryntum/support#6033] opened 2023-01-24 13:27 UTC
Hi,

We have been struggling with Bryntum Gantt for 5-6 months. We are experiencing issues and difficulties on a daily basis. Maybe we are doing something wrong. But as experienced JavaScript, TypeScript, and React developers, we believe that our problems to a large extend are related to bugs, inconsistencies and anti-patterns.

We are not sure we can continue with our current approach. We are jumping from one problem to the next and productivity has reached a new low. Let's take a very simple example that demonstrates just one of our problems.

We want to create a gantt chart that initially shows this (Image 1):
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/10479064/214291279-0c9fac94-aed7-4142-a7a1-b2b2b1f4df3b.png">

With a click of a button we'd like to introduce a milestone so it shows this (Image 2):
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/10479064/214291509-387b8fd3-b305-4720-8d52-fa056254cacd.png">

Please tell me why the code below doesn't work (based on examples/frameworks/react/typescript/basic)
[Bryntum-1.zip](https://github.com/bryntum/support/files/10489428/Bryntum-1.zip)

The demo initially shows the data as expected (Image 1). But when we click the "Load next set of data" button, we'd expect Gantt to show what is displayed in Image 2 - but it doesn't update.

```
import React, { FunctionComponent } from 'react';
import { BryntumGantt, BryntumProjectModel } from '@bryntum/gantt-react';
import { ganttData as ganttData1 } from "./AppData1"; // Initial data
import { ganttData as ganttData2 } from "./AppData2"; // Like ganttData1 + a milestone + a dependency
import { ganttConf } from "./AppConfig";
import './App.scss';

const columns = ganttData1().columns;
const datasets = [ganttData1(), ganttData2(), ganttData1(), ganttData2(), ganttData1(), ganttData2()];

const App: FunctionComponent = () => {
    const projectModel = React.useRef<BryntumProjectModel | null>(null);

    let [dataSetIndex, setDataSetIndex] = React.useState(0);
    const ganttData = datasets[dataSetIndex < datasets.length ? dataSetIndex : datasets.length - 1];

    return (
        <>
            {<BryntumProjectModel
                ref={projectModel}
                startDate={ganttData.startDate}
                endDate={ganttData.endDate}
                tasks={ganttData.tasks}
                dependencies={ganttData.dependencies}
                eventStore={{}}
            />}
            { projectModel &&
                <BryntumGantt
                    project={projectModel}
                    columns={columns}
                    criticalPathsFeature={{ disabled: true }}
                    {...ganttConf}
                />
            }
            <br /><br />
            <button onClick={() => { setDataSetIndex(dataSetIndex + 1); }} disabled={dataSetIndex === datasets.length - 1}>Load next set of data</button>
        </>
    );
};

export default App;
```

If we avoid the ProjectModel, and instead assign tasks and dependencies directly to the Gantt component, then it _almost_ works. The milestone and dependency shows up - but in the wrong place.

```
import React, { FunctionComponent } from 'react';
import { BryntumGantt } from '@bryntum/gantt-react';
import { ganttData as ganttData1 } from "./AppData1"; // Initial data
import { ganttData as ganttData2 } from "./AppData2"; // Like ganttData1 + a milestone + a dependency
import { ganttConf } from "./AppConfig";
import './App.scss';

const columns = ganttData1().columns;
const datasets = [ganttData1(), ganttData2(), ganttData1(), ganttData2(), ganttData1(), ganttData2()];

const App: FunctionComponent = () => {
    let [dataSetIndex, setDataSetIndex] = React.useState(0);
    const ganttData = datasets[dataSetIndex < datasets.length ? dataSetIndex : datasets.length - 1];

    return (
        <>
            <BryntumGantt
                columns={columns}
                startDate={ganttData.startDate}
                endDate={ganttData.endDate}
                tasks={ganttData.tasks}
                dependencies={ganttData.dependencies}
                criticalPathsFeature={{ disabled: true }}
                {...ganttConf}
            />
            <br /><br />
            <button onClick={() => { setDataSetIndex(dataSetIndex + 1); }} disabled={dataSetIndex === datasets.length - 1}>Load next set of data</button>
        </>
    );
};

export default App;
```

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/10479064/214296736-67bebfcb-1378-4274-adbe-7aff0439d9b2.png">

If we load ganttData2 initially, then the milestone shows up at the expected position.

The fact that Bryntum Gantt doesn't reflect the state of our application is an anti-pattern which makes it difficult to work with. But in the example above tasks and dependencies are not among the special "configs" which cannot be updated once rendered. And the fact that the component is not rendered deterministically (it renders ganttData2 differently, depending on whether it was fed to the Gantt component on the first or second render) is also an anti-pattern.

First of all I would like to know if we are stumbling into bugs in the examples above, or if there is some secret property that needs to be set for things to work like React components should.

Secondly, would we be better off avoiding the React wrapper entirely - perhaps it's mainly for demo purposes ?

I would also very much appreciate some advise on how to proceed. While there might be an explanation as to why our examples misbehave, imagine being a developer having to work with this. Even though there is a lot of documentation available, often times we don't know what to look for, and the TypeScript definitions are not exactly helping ([hint](https://github.com/bryntum/support/issues?q=is%3Aissue+is%3Aopen+typescript)).

-- Thanks for any useful input in advance

**Comment by matsbryntse** [comment] 2023-01-25 11:07
Dupe of https://github.com/bryntum/support/issues/6039 ?

**Comment by FlowIT-JIT** [comment] 2023-01-25 12:15
@matsbryntse I believe we reported that problem last year. It was initially considered a bug - until it was rejected with a suggestion to set syncDataOnLoad to _false_.

https://github.com/bryntum/support/issues/5336
and
https://github.com/bryntum/support/issues/5336

Am I wrong in assuming this is the same problem? If it indeed is the same problem, then why is it accepted as a bug today and was rejected as "by design" last year?

**Comment by jsakalos** [comment] 2023-01-25 13:33
Although `syncDataOnLoad` issue is still there, the real problem here is this line:
```
               eventStore={{}}
```

I'm not sure where it comes from but it has the devastating effect. Technically, eventStore and taskStore are synonyms in Gantt so setting eventStore to an empty object sets taskStore to the empty object which has unpredictable results. Remove this line and your demo will work.

You can turn off `syncDataOnLoad` this way:
```
    return (
        <>
            <BryntumProjectModel
                ref={projectModel}
                startDate={ganttData.startDate}
                endDate={ganttData.endDate}
                tasks={ganttData.tasks}
                taskStore={new TaskStore({
                    syncDataOnLoad:false
                })}
                dependencies={ganttData.dependencies}
            />
```

**Comment by FlowIT-JIT** [comment] 2023-01-25 13:52
Thanks @jsakalos - very helpful. We have tried all sorts of things, so it's probably a left over from a test where we fiddled with syncDataOnLoad. Thank you.

I'm still concerned with the non-deterministic behaviour - I hope it will be resolved this time 🤞😊

**Comment by jsakalos** [comment] 2023-01-25 15:02
> I'm still concerned with the non-deterministic behaviour - I hope it will be resolved this time

I'm not sure that I fully get what exactly should we fix. Anyway, we are eager to improve our products and their React integration. Give us please some specifics that we could relate to the code.

If you mean updating the gantt when changing data – that should be resolved by the above changes and after fixing `syncDataOnLoad` bug it won't even need the workaround.

**Closed** 2023-06-27 11:27 UTC
