### ISSUE TITLE
Events for dependencies not being fired in React application

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#7362] opened 2023-08-23 13:14 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=25995&p=129578#p129578)

- Go to React inline data demo
- Add some listeners related to dependencies
```
<BryntumSchedulerPro
                ref={schedulerpro}
                project={project}
                {...schedulerProConfig}
                dependenciesFeature={true}
                onBeforeDependencyAdd={e => {
                    console.log(e, 'called onBeforeDependencyAdd');
                }}
                onBeforeDependencySave={e => {
                    console.log(e, 'called onBeforeDependencySave');
                }}
                onDependenciesDrawn={e => {
                    console.log(e, 'called onDependenciesDrawn');
                }}
                onBeforeDependencyCreateDrag={e => {
                    console.log(e, 'called onBeforeDependencyCreateDrag');
                }}
                onBeforeDependencyDelete={e => {
                    console.log(e, 'called onBeforeDependencyCreateDrag');
                }}
            />
```
- The listeners are not being triggered (in plain JS they work correctly), the types are correct as well, they are present there.

**Comment by jsakalos** [comment] 2023-12-01 07:47
This is not a bug. The docs say:

<img width="965" alt="Screenshot 2023-12-01 at 08 44 43" src="https://github.com/bryntum/support/assets/204844/b446e2e9-72ad-4eed-af89-34ff707fd5ea">

but the feature is not enabled in the showcase. Just add:
```
dependencyEditFeature={true} 
```

to `<BryntumSchedulerPro ...` properties and events start to fire as documented.

**Comment by jsakalos** [comment] 2023-12-01 07:57
As said, this is not a bug. Closing the issue.

**Closed by jsakalos** 2023-12-01 07:57 UTC
Labels: bug, invalid, react, high-priority, forum, large-account
