### ISSUE TITLE
Time axis breaks after scrolling leftwards a long way

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#105] opened 2019-12-18 12:27 UTC
Possibly related: https://github.com/bryntum/support/issues/40

1. Open configuration demo
2. Zoom out max
3. Drag create new event and scroll it right to make it super long
4. Save 
5. Scroll leftwards a long way
6. Note broken time axis

Video: https://monosnap.com/file/K9OYbSmeSEWK4Ajw2IZfz2eqE79YuC

<img width="1680" alt="Screenshot 2019-12-18 at 13 26 15" src="https://user-images.githubusercontent.com/218570/71086333-fc9bc000-2199-11ea-8d66-5abd40493d63.png">

**Comment by ExtAnimal** [comment] 2019-12-18 15:37
Focus an event pm the same row to the right of the very wide event, then use left arrow to navigate back to the very wide event:

![timeaxisheaderbug](https://user-images.githubusercontent.com/200516/71099990-1b0ab700-21ac-11ea-9f42-04240693ca24.gif)

**Comment by ExtAnimal** [comment] 2019-12-19 09:05
On further investigation, it's when there's an animated scroll. The response to scrolling which updates the scheduler is in the next AF *after* each scroll event, but the last one will be in the same AF that the animation function is using to trigger the final position.

The fix is in this code block in `SubGrid.js`

```
    initScroll() {
        const
            me                     = this,
            scroller               = me.scrollable,
            virtualScrollerElement = me.virtualScrollerElement;

        me.syncScrollingPartners = me.createOnFrame(me.syncScrollingPartnersNow);

        if (BrowserHelper.isFirefox) {
            scroller.element.addEventListener('wheel', event => {
                if (event.deltaX) {
                    scroller.x += event.deltaX;
                    event.preventDefault();
                }
            });
        }

        scroller.yScroller = me.grid.scrollable;

        // Add our Scroller to the controlling GridScroller
        scroller.yScroller.addScroller(scroller);

        // Create a Scroller for the fake horizontal scrollbar so that it can partner
        me.fakeScroller = new Scroller({
            element   : virtualScrollerElement,
            overflowX : true
        });

        // Sync scrolling partners (header, footer) when our xScroller reports a scroll.
        // Also fires horizontalscroll
        scroller.on({
            scroll    : 'onSubGridScroll',
            scrollend : 'onSubGridScrollEnd',
            thisObj   : me
        });

        scroller.addPartner(me.fakeScroller, 'x');
        if (me.header) {
            scroller.addPartner(me.header.scrollable, 'x');
        }
        if (me.footer) {
            scroller.addPartner(me.footer.scrollable, 'x');
        }
    }

    onSubGridScrollEnd() {
        this.scrolling = false;
        if (!this.forceScrollUpdate) {
            this.onSubGridScroll();
        }
    }

    onSubGridScroll() {
        // Force direct update, without waiting for next animation frame
        // TODO: Only used in Scheduler, could perhaps live in Scheduler specific SubGrid in the future
        if (this.forceScrollUpdate) {
            this.syncScrollingPartners();
            this.forceScrollUpdate = false;
        }
        else {
            this.syncScrollingPartners();
        }
    }

    set scrolling(scrolling) {
        this._scrolling = scrolling;
        this.grid.bodyContainer.classList[scrolling ? 'add' : 'remove']('b-scrolling');
    }

    get scrolling() {
        return this._scrolling;
    }

    /**
     * This syncs the horizontal scroll position of the header and the footer with
     * the horizontal scroll position of the grid. Usually, this will be called automatically
     * when the grid scrolls. In some cases, such as a refresh caused by column changes
     * it will need to be called from elsewhere.
     * @internal
     */
    syncScrollingPartnersNow(addCls = true) {
        const subGrid    = this,
            { grid }   = subGrid,
            scrollLeft = subGrid.scrollable.x;

        if (!subGrid.scrolling && addCls) {
            subGrid.scrolling = true;
        }

        grid.trigger('horizontalScroll', { subGrid, grid, scrollLeft });
    }

```

**Comment by ExtAnimal** [comment] 2019-12-19 14:04
Dupe of https://github.com/bryntum/support/issues/58

**Comment by ExtAnimal** [comment] 2019-12-20 07:41
https://github.com/bryntum/bryntum-suite/pull/311

**Closed** 2020-01-17 10:44 UTC
Labels: bug, high-priority, resolved
