### ISSUE TITLE
Add `tabIndex` config to Button

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#8166] opened 2024-01-02 20:16 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=27228&p=137367#p137367)

"Now I have another problem, the tabIndex of a button. I guess this configuration must be in the Widget. It is possible?"

**Comment by dongryphon** [comment] 2024-01-03 17:53
Duplicate of https://github.com/bryntum/support/issues/8010

**Comment by dongryphon** [comment] 2024-01-03 17:54
Perhaps we should make this one "Add tabIndex to Button"?

**Comment by dongryphon** [comment] 2024-01-03 18:01
@marciogurka feel free to push back on targeting only `Button` for this one. See [my comment](https://github.com/bryntum/support/issues/8010#issuecomment-1872630513) on why adding to `Widget` would be problematic

**Closed** 2024-03-05 10:26 UTC
Labels: feature request, resolved, forum, large-account, OEM
