### ISSUE TITLE
Make configurable maximum resource capacity in ResourceHistogram

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4396] opened 2022-03-22 10:52 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=44&t=20710&p=102699#p102699)

We use Scheduler Pro with connection to Histogram to display the capacity of resources depending on the scheduled events. Currently, for each event that goes over a day, it assumes a utilization of 100% (24h). We would like to increase this to show us the capacity progression. Is there a way to individually increase the maximum display of 24h/day (e.g. to 250h/day) in histogramconfig?

**Comment by arcady-zherdev** [comment] 2022-09-27 05:23
Similar ticket: https://github.com/bryntum/support/issues/833

**Comment by canonic-epicure** [comment] 2024-03-04 05:05
Closing as duplicate of https://github.com/bryntum/support/issues/833 Please feel free to re-open with extra details.

**Closed by canonic-epicure** 2024-03-04 05:05 UTC
Labels: duplicate, feature request, forum, large-account
