### ISSUE TITLE
Events are disappearing on vertical scroll

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#7479] opened 2023-09-13 14:30 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=26226&p=130697#p130697)

Hi, 
We are having issue that tasks cards disappear on scheduler when user vertically scroll the scheduler.

On investigation it seems the task event presents in the DOM but are getting css "top" value incorrect sometimes and task tickets shifts vertically on the scheduler.

Demo:
![chrome_oXczOZEFiV](https://github.com/bryntum/support/assets/75997756/3c3e1789-0599-407e-beef-07cd68e04244)

I have attached a test case  you can run in your basic demo example https://bryntum.com/products/scheduler/examples/basic/ to check and reproduce the issue

**Comment by isglass** [comment] 2023-09-19 12:16
Caused by event being assigned to the same resource multiple times

**Comment by isglass** [comment] 2023-09-20 18:20
User reports issue is still there without duplicate assignments, have requested more information on how to reproduce

**Closed** 2023-10-05 12:15 UTC
Labels: bug, resolved, forum
