### ISSUE TITLE
"Drag unplanned tasks" tab not working in Salesforce sandbox

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#9373] opened 2024-06-12 14:48 UTC
https://bryntum-dev-ed.develop.lightning.force.com/lightning/n/SchedulerProTempDemo

Try dragging task from the external grid, no reaction.

**Comment by bmblb** [comment] 2024-06-19 09:07
Not reproducible in MS Edge. Tasks can be dropped only to allowed zones. Drag works for me as well as drop. Which browser was it?

**Comment by bmblb** [comment] 2024-06-19 09:28
Apparently it is a Mac specific issue, works fine on windows in chrome and edge, with and without LWS

![Screenshot 2024-06-19 at 11 24 12](https://github.com/bryntum/support/assets/45400762/12da853c-97a9-40dc-b89d-31332bd882b9)

**Comment by chuckn0rris** [comment] 2024-06-19 10:59
Fixed in master, will be there with 6.0 release
https://github.com/bryntum/support/assets/7203098/74f2734d-29ab-4ba5-b135-bd9677a3bb38

**Comment by chuckn0rris** [comment] 2024-06-20 07:11
Reopened, didn't work when LockerService

**Comment by chuckn0rris** [comment] 2024-11-16 10:52
Fixed in bounds of https://github.com/bryntum/support/issues/10195

**Closed by chuckn0rris** 2024-11-16 10:52 UTC
Labels: bug, high-priority, in progress, salesforce
