### ISSUE TITLE
Enable showing events in a different timezone

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1407] opened 2020-08-25 06:02 UTC
Should be possible to set manual timezone by user.
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=54&t=14992&p=75886)
https://www.bryntum.com/forum/viewtopic.php?f=54&t=22338&p=110505#p110505

**Comment by isglass** [comment] 2022-12-21 13:58
Closing as duplicate of bryntum/support#1533

**Closed by isglass** 2022-12-21 13:58 UTC
Labels: feature request, resolved, forum
