### ISSUE TITLE
Printing Calendar Agenda view results in empty page(s)

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#4674] opened 2022-05-25 07:33 UTC
Might be browser related. Check forum post for details.

[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=1&t=21373&p=105812#p105812)

To reproduce:

Go to https://bryntum.com/examples/calendar/print/
Click Agenda view
Then Click Print.

**Comment by Syrah-NL** [comment] 2022-05-25 08:12
It might be browser-related, because when I try to print on Android (also Chrome):

https://imgur.com/oxkNGlk

And also in "Desktop view":

https://imgur.com/1KeI48l

**Comment by ExtAnimal** [comment] 2022-10-01 08:48
This is a duplicate of a duplicate.

https://github.com/bryntum/support/issues/4016
https://github.com/bryntum/support/issues/3884

To repeat the comments from the previous tickets. We have tried several times to work on this.

It's a Grid, and fundamentally the grid printing doesn't handle complex, variable row height, multi page printing.

**Comment by matsbryntse** [comment] 2023-04-03 06:48
Duplicate

**Closed by matsbryntse** 2023-04-03 06:48 UTC
Labels: bug, high-priority, forum
