### ISSUE TITLE
Uninstall global listeners when all Bryntum widgets are destroyed

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#7112] opened 2023-07-04 10:05 UTC
The frameworks require to fully remove Bryntum widgets, including installed global listeners, is some cases, for example when navigation out of the page that contains a Bryntum component. 

We need a way how to sense that all widgets are gone and detach the global events in that case.

This can also be done in the framework application but we should not impose this responsibility on the users.

[Forum post](https://forum.bryntum.com/viewtopic.php?t=25413)

```
import { Component, OnDestroy, OnInit, ViewChild} from '@angular/core';
import { GlobalEvents } from '@bryntum/scheduler';

@Component({
  selector: 'app-scheduler',
  templateUrl: './scheduler.page.html',
  styleUrls: ['./scheduler.page.scss', './scheduler.stockholm.css']
})
export class SchedulerPage {

  constructor() { }

  ionViewWillLeave() {
    // @ts-ignore
    GlobalEvents.detachEvents();
  }

}
```

**Comment by chuckn0rris** [comment] 2023-08-23 11:11
Dupe of this https://github.com/bryntum/support/issues/3212

**Closed by chuckn0rris** 2023-08-23 11:11 UTC
Labels: bug, premium, forum, large-account, OEM
