### ISSUE TITLE
React: Unexpected token on run/build

### ISSUE THREAD

**Issue by SergeyMaltsev** [bryntum/support#221] opened 2020-01-23 08:36 UTC
Reported here
https://www.bryntum.com/forum/viewtopic.php?p=68525

Webpack loader can't recognize async generator functions.

```
  63262 |  * @private
  63263 |  */
> 63264 | Exporter.prototype.pagesExtractor = async function * pagesExtractor() {
        |                                                    ^
  63265 |     yield '';
  63266 | };
  63267 | Exporter._$name = 'Exporter';
```

**Comment by bmblb** [comment] 2020-01-23 09:03
it appears that open source plugins lack language feature support. async generators are perfectly valid. Brief history of the problem:
1. initially that async generator was a function on a class
2. uglify-js didn't like that syntax, so after some investigation we switched to terser, which didn't complain. here is a commit which added support https://github.com/terser/terser/issues/97
3. but some other webpack plugin was changing that async generator to regular async function (javascript-obfuscator likely, not maintained anymore but open for PRs https://github.com/javascript-obfuscator/javascript-obfuscator/issues/402)
4. this method moved from class definition to setting it directly on prototype

First we need to understand which plugin is complaining. Probably it is uglify js or smth. We switched to terser, so did the webpack as of release 4.26 https://github.com/webpack/webpack/releases/tag/v4.26.0

**Comment by jsakalos** [comment] 2020-02-06 08:23
The issue was most likely caused by the custom project configuration that led us to improve our React integration guide. AFAIK we were not able to reproduce the problem with our sources alone.

Closing for now, can be re-opened if the error re-occurs.

**Closed by jsakalos** 2020-02-06 08:23 UTC
Labels: bug, high-priority, react
