### ISSUE TITLE
Adding partners dynamically breaks cell rendering

### ISSUE THREAD

**Issue by pmiklashevich** [bryntum/support#2523] opened 2021-03-17 16:57 UTC
https://www.bryntum.com/forum/viewtopic.php?p=84136#p84136

http://lh/bryntum-suite/scheduler/examples/partners/
```
const scheduler2 = new Scheduler({
    // partner           : scheduler1,
    // hideHeaders       : true,
...
});
scheduler2.partner = scheduler1;
```
Scroll second grid top the right. See header cells are misrendered

https://user-images.githubusercontent.com/57486733/111505969-37542580-875a-11eb-813e-17961f8b58b0.mov

If make timeaxis longer, the header of the second grid is not rendered at all, and the resources are not selectable
```
const scheduler1 = new Scheduler({
...
    startDate  : new Date(2018, 0, 1, 6),
    endDate    : new Date(2018, 0, 10, 20),
    viewPreset : 'minuteAndHour'
});
```
See scrolls are not synced. If scroll right, there is no header in second scheduler, and resources are not selectable. If scroll left to the events, the resource selection works.
<img width="984" alt="Снимок экрана 2021-03-17 в 19 54 44" src="https://user-images.githubusercontent.com/57486733/111506485-b9444e80-875a-11eb-9c7f-f4998eb6cb5a.png">

**Comment by bmblb** [comment] 2021-03-29 10:42
Dupe of #2557 which is resolved now

**Comment by pmiklashevich** [comment] 2021-03-29 11:16
Confirm the fix for 2557 fixes the scrolling issue. Regarding the scroll position which is not equal to 0, it happens only when second grid view preset and dates are different. They are different when they are not specified explicitly. So  the grid timelines show different view. And when they get partnered scroll gets synced and it is not at the beginning. Therefore it works as expected.

**Closed** 2021-03-29 12:56 UTC
Labels: bug
