### ISSUE TITLE
Undo add interval not working as expected

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#6275] opened 2023-03-01 09:14 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=24043&p=119007#p119007)

Hello

When creating an interval and trying to undo, it can still be found in the Calendars interval store:

Done on this example with the 3 buttons on the top https://bryntum.com/products/schedulerpro/examples-scheduler/undoredo/
![undo_redo_issue_intervalStore.gif](https://forum.bryntum.com/download/file.php?id=20965)

With the attached code.
[undoredo_error_calendar_intervals.txt](https://github.com/bryntum/support/files/10859096/undoredo_error_calendar_intervals.txt)

**Comment by canonic-epicure** [comment] 2023-05-17 06:33
It seems the issue is no longer reproducible?

https://github.com/bryntum/support/assets/72431/aaa41d91-8d05-41e3-aecc-a2193db4e8af

**Comment by canonic-epicure** [comment] 2023-07-20 09:16
Going to close this one, please feel free to re-open with the new steps to reproduce.

**Closed by canonic-epicure** 2023-07-20 09:16 UTC
Labels: bug, info requested, not reproducible, forum, OEM
