### ISSUE TITLE
[ANGULAR] Scheduler Drag between schedulers: bottom scheduler loses headers on scrolling

### ISSUE THREAD

**Issue by jsakalos** [bryntum/support#2552] opened 2021-03-23 12:52 UTC
To reproduce, start the demo, zoom in and scroll horizontally.

This does not happen in vanilla demo - maybe it is theme related.

<img width="1050" alt="Screen Shot 2021-03-23 at 13 51 41" src="https://user-images.githubusercontent.com/204844/112149145-f8512480-8bde-11eb-8e45-38cd3e678c8f.png">

**Comment by pmiklashevich** [comment] 2021-03-23 16:32
May be related to https://github.com/bryntum/support/issues/2523
Happens when adding partners dynamically

**Comment by bmblb** [comment] 2021-03-29 10:42
Duplicate of: #2557

**Closed by bmblb** 2021-03-29 10:42 UTC
Labels: bug, bugbash
