### ISSUE TITLE
Add isSelectable template method

### ISSUE THREAD

**Issue by matsbryntse** [bryntum/support#3692] opened 2021-11-09 10:22 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=18131&p=95858#p95858)

Great! For the same reasons, could you also please implement isSelectable for TaskBoard.view.mixin.TaskSelection? We've recently found a need for that as well.

**Comment by isglass** [comment] 2022-08-08 06:34
Duplicate of https://github.com/bryntum/support/issues/4213, which is about to be resolved

**Closed by isglass** 2022-08-08 06:34 UTC
Labels: duplicate, feature request, premium, forum, OEM
