### ISSUE TITLE
[Vue2] [Calendar] Using event selection mixin

### ISSUE THREAD

**Issue by dcruz1990** [bryntum/support#6175] opened 2023-02-14 21:38 UTC
Hello, i'm not sure on how to use this mixing, i just want to, based on certain type of event, disable or enable selection. 

Things i tried:
1. In the modes config object, passed `isEventSelectable()` , no works.
2. In the calendar instantiation, doesn't work either.
3. In the examples, like this:
![image](https://user-images.githubusercontent.com/43586145/218868650-78eecf8d-8eab-4237-a7fa-e03fe1ed8cd7.png)

Anyone can explain where to put or how to use [https://bryntum.com/products/calendar/docs/api/Calendar/view/mixin/EventSelection#config-eventSelectionDisabled](asd)

**Comment by ExtAnimal** [comment] 2023-02-15 08:35
Duplicate of https://github.com/bryntum/support/issues/6177

**Closed by ExtAnimal** 2023-02-15 08:35 UTC
