### ISSUE TITLE
`EventHandlers` are not searchable in docs

### ISSUE THREAD

**Issue by ghulamghousdev** [bryntum/support#8557] opened 2024-02-15 12:31 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=43&t=28018&p=140640#p140640)

When try to find an event handler in the documentation search it doesn't show the searched values, like the print below:

![Screenshot_7.png](https://forum.bryntum.com/download/file.php?id=26909)

**Comment by ExtAnimal** [comment] 2024-02-15 13:11
Dupe of https://github.com/bryntum/support/issues/8555

These two events should be hoisted to the `Container` class with appropriate warnings that they are only fired if the Container uses `card` layout.

**Comment by matsbryntse** [comment] 2024-02-17 14:58
Not a duplicate

**Closed** 2024-02-22 11:54 UTC
Labels: bug, resolved, docs, forum, OEM
