### ISSUE TITLE
Just created task has not been removed on cancel click in taskEditor

### ISSUE THREAD

**Issue by chuckn0rris** [bryntum/support#1522] opened 2020-09-16 10:32 UTC
1. Open any of SchedulerPro's examples.
2. Double click to create a new task.
3. Click Cancel in TaskEditor.

Task has not beed removed. But it does in the Scheduler.
Reproduced in master.

**Comment by matsbryntse** [comment] 2020-09-16 11:25
Dupe of https://github.com/bryntum/support/issues/1503

**Closed by matsbryntse** 2020-09-16 11:25 UTC
Labels: bug
