### ISSUE TITLE
useRawData default to true makes create new record not work correctly

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#9701] opened 2024-07-30 13:57 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=29942&p=151645#p151645)

"useRawData default to true causing a bug. The bug is if I have a defaultValue set for fields in my model class and then I try to create a record with data, the default values in model class replaces my provided data with the defaults.

```
import { Model, Store, ProjectModel } from '../../build/schedulerpro.module.js?478335';
import shared from '../_shared/shared.module.js?478335';

class MyModel extends Model {
  static get fields() {
    return [
      { name: "myName", dataSource: "name", defaultValue: "novalue" },
      { name: "isDefaultView", dataSource: "is_default_view", type: "boolean", defaultValue: false },
    ]
  }
}

const testStore = new Store({
  storeId: "testStore",
  modelClass: MyModel,
  // useRawData: false
});

const testProject = new ProjectModel({
  crudStores: [
    testStore
  ],
  loadUrl: "https://www.test.com",
})
console.log(testProject)
testProject.useRawData = false;

const viewToAdd = testStore.createRecord({
    myName: "test",
    isDefaultView: true,
});
console.log(viewToAdd.myName, viewToAdd.isDefaultView); // logs: novalue, false
```
As you can see from the output my provided values are ignored but If I sets the useRawData in store to false it works fine."

Live CodePen - https://codepen.io/marciogurka/pen/xxogjPW

**Comment by isglass** [comment] 2024-07-31 13:45
Duplicate of https://github.com/bryntum/support/issues/9712

**Closed by isglass** 2024-07-31 13:46 UTC
Labels: bug, duplicate, forum, OEM
