### ISSUE TITLE
Enabling fillTicks removes nonWorkingTime background

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5481] opened 2022-10-26 12:09 UTC
[Forum post](https://www.bryntum.com/forum/viewtopic.php?f=51&t=22739&p=112425#p112425)

"Hi Bryntum Support,

I think the new fillTicks feature is very nice. I like it.
I'm trying introducing it into my product.

However, when I enable the fillTicks flag, the nonWorkingTime background is gone.
It can be reproduced on https://bryntum.com/examples/gantt/fill-ticks/.

[How to reproduce]

- open [fill ticks demo](https://bryntum.com/examples/gantt/fill-ticks/)
- execute the code below.
- switch the fillTicks option.

```
gantt.project.calendar.addInterval({
    startDate: '2022-01-11 00:00',
    endDate: '2022-01-12 00:00',
    isWorking: false,
});
gantt.timeAxisViewModel.update();

```

[Expected]
2022-01-11 is filled by non working time background color regardless to the fillTicks option.

[Actual]
2022-01-11 is NOT filled only when enabling the fillTicks option.

Please fix it as soon as possible!
It's a major bug for me."

https://user-images.githubusercontent.com/16693227/198022272-a9e1865e-9086-4217-8fe6-f2a61b8d8411.mp4

**Comment by taauntik** [comment] 2022-10-31 06:34
asking for when it's going to be fixed [here](https://forum.bryntum.com/viewtopic.php?f=51&t=22739&p=112653#p112653)

**Comment by canonic-epicure** [comment] 2023-01-10 09:55
Might be a duplicate of https://github.com/bryntum/support/issues/5797

**Comment by canonic-epicure** [comment] 2023-01-11 11:11
Confirmed, a duplicate of #5797, please track that ticket.

**Closed by canonic-epicure** 2023-01-11 11:11 UTC
Labels: bug, high-priority, premium, forum, OEM
