### ISSUE TITLE
Task should be able to reposition right below the Project

### ISSUE THREAD

**Issue by taauntik** [bryntum/support#8774] opened 2024-03-10 11:51 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=52&t=28294&p=142228#p142228)

Hi everyone,

I am facing an issue with Bryntum Gantt,

When I try to drag a newly created task right below the project it does not reposition it instead it Converts it into a new project and places it at the bottom.

I am also attaching a video with a demostration. 

https://github.com/bryntum/support/assets/75997756/370dea67-55fd-4bec-9957-a9f42f7da42e

Thanks

**Comment by ghulamghousdev** [comment] 2024-03-11 05:52
I think this is duplicate of this ticket https://github.com/bryntum/support/issues/3252.

**Comment by matsbryntse** [comment] 2024-07-07 16:12
I can no longer reproduce this in v6. Please confirm if you can still reproduce and we'll reopen.

**Closed by matsbryntse** 2024-07-07 16:12 UTC
Labels: bug, forum
