### ISSUE TITLE
Started tasks should preserve their start date value

### ISSUE THREAD

**Issue by arcady-zherdev** [bryntum/support#6769] opened 2023-05-12 10:41 UTC
Started tasks should behave similar to manually scheduled ones:

1. they don't fallback to the project start 
2. they aren't pinned with a constraint when moving
3. Tasks should be rescheduled if the % done is set to 0

Implementing this will fix: https://github.com/bryntum/support/issues/6766

Related https://forum.bryntum.com/viewtopic.php?t=11101

**Comment by canonic-epicure** [comment] 2024-07-03 10:05
Duplicate of https://github.com/bryntum/support/issues/3211?

**Comment by canonic-epicure** [comment] 2024-07-09 11:10
Closing as duplicate of #3211.

**Closed by canonic-epicure** 2024-07-09 11:10 UTC
Labels: feature request, high-priority, ready for review
