### ISSUE TITLE
Add HTML content support for the ResourceTimeRange feature

### ISSUE THREAD

**Issue by marciogurka** [bryntum/support#5839] opened 2022-12-27 13:27 UTC
[Forum post](https://forum.bryntum.com/viewtopic.php?f=44&t=23379&p=115696#p115696)

"Hi, Is there any body rendered event for the resource time range? or html content is supported for the name property? What I want to achieve you can see in the attached mockup.
Following this demo:
https://bryntum.com/products/scheduler/examples/resourcetimeranges/"
![resource_time_range.png](https://forum.bryntum.com/download/file.php?id=20081)

As you can see in the [documentation](https://bryntum.com/products/scheduler/docs/api/Scheduler/model/ResourceTimeRangeModel#field-name)

The name property currently supports only a string.

**Comment by pmiklashevych** [comment] 2023-08-09 06:59
This is a quick workaround. Please share with the user. I cannot post to the forums due to missing subscription.

```
import { ResourceTimeRanges, Override } from '@bryntum/schedulerpro';

// Use it until https://github.com/bryntum/support/issues/5839 is fixed
class ResourceTimeRangesOverride {
  static get target() {
    return {
      class: ResourceTimeRanges,
      product: 'schedulerpro',
    }
  }

  // Provides renderer for ResourceTimeRanges
  onEventDataGenerated(renderData) {
    const { eventRecord } = renderData;

    // Calls node_modules/@bryntum/schedulerpro/source/lib/Scheduler/feature/base/ResourceTimeRangesBase.js::onEventDataGenerated
    this._overridden.onEventDataGenerated.call(this, renderData);

    // Calls node_modules/@bryntum/schedulerpro/source/lib/Scheduler/feature/ResourceTimeRanges.js::shouldInclude
    // If true, eventRecord is a ResourceTimeRange
    if (this.shouldInclude(eventRecord)) {
      // Remove text
      delete renderData.eventContent.text;

      // Add html
      renderData.eventContent.html = `
        <div class="reservation">
          <div class="reservation-amount">${eventRecord.reservationAmount}</div>
          <div class="reservation-price">${eventRecord.name}</div>
          <div class="reservation-minNight">${eventRecord.minNight}</div>
        </div>
      `;
    }
  }
}

Override.apply(ResourceTimeRangesOverride);
```

**Comment by matsbryntse** [comment] 2023-08-09 07:17
@pmiklashevych This is now fixed as part of 4922! I've added you to our license too so you can post in the forums :)
Duplicate of https://github.com/bryntum/support/issues/4922

**Closed by matsbryntse** 2023-08-09 07:17 UTC
Labels: feature request, forum
